package gotreesitter

type PerfCounters struct {
	MergeCalls                      uint64
	MergeDeadPruned                 uint64
	MergePerKeyOverflow             uint64
	MergeReplacements               uint64
	StackEquivalentCalls            uint64
	StackEquivalentTrue             uint64
	StackEqHashMissSkips            uint64
	StackCompareCalls               uint64
	ConflictRR                      uint64
	ConflictRS                      uint64
	ConflictOther                   uint64
	ForkCount                       uint64
	FirstConflictToken              uint64
	MaxConcurrentStacks             uint64
	LexBytes                        uint64
	LexTokens                       uint64
	ReuseNodesVisited               uint64
	ReuseNodesPushed                uint64
	ReuseNodesPopped                uint64
	ReuseCandidatesChecked          uint64
	ReuseSuccesses                  uint64
	ReuseLeafSuccesses              uint64
	ReuseNonLeafChecks              uint64
	ReuseNonLeafSuccesses           uint64
	ReuseNonLeafBytes               uint64
	ReuseNonLeafNoGoto              uint64
	ReuseNonLeafNoGotoTerm          uint64
	ReuseNonLeafNoGotoNt            uint64
	ReuseNonLeafStateMiss           uint64
	ReuseNonLeafStateZero           uint64
	MergeHashZero                   uint64
	GlobalCapCulls                  uint64
	GlobalCapCullDropped            uint64
	ReduceChainSteps                uint64
	ReduceChainMaxLen               uint64
	ReduceChainBreakMulti           uint64
	ReduceChainBreakShift           uint64
	ReduceChainBreakAccept          uint64
	ReduceChainHintCandidates       uint64
	ReduceChainHintTaken            uint64
	ReduceChainHintSteps            uint64
	ReduceChainHintTerminalOK       uint64
	ReduceChainHintTerminalMismatch uint64
	ReduceChainHintLimit            uint64
	ReduceChainHintDead             uint64
	ReduceChainHintUnexpected       uint64
	ParentChildPointers             uint64
	ReduceChildrenFastGSS           uint64
	ReduceChildrenAllVis            uint64
	ReduceChildrenNoAlias           uint64
	ReduceChildrenScratch           uint64
	ReduceScratchNoAlias            uint64
	ReduceScratchGeneral            uint64
	ForestReduceCalls               uint64
	ForestReduceZero                uint64
	ForestReduceLinearNoExtras      uint64
	ForestReduceDFS                 uint64
	ForestReduceDFSLinks            uint64
	ForestReduceDFSMultiLinkSteps   uint64
	ForestReduceDFSExtraLinks       uint64
	ForestReduceDFSVisits           uint64
	ForestReduceDFSPathEntries      uint64
	ForestReduceGotoHits            uint64
	ForestReduceGotoMisses          uint64
	ForestReduceMaxPathLen          uint64
	ForestReduceMaxChildCount       uint64
	ForestCoalesceCalls             uint64
	ForestCoalesceNewNodes          uint64
	ForestCoalesceLinkAppends       uint64
	ForestCoalesceDedupHits         uint64
	ForestCoalesceDedupReplacements uint64
	ForestCoalescePreCapDrops       uint64
	ForestCoalesceCapDrops          uint64
	ForestCoalesceCapReplacements   uint64
	ExtraNodes                      uint64
	ErrorNodes                      uint64
	MergeStacksInHist               [maxGLRStacks + 2]uint64
	MergeAliveHist                  [maxGLRStacks + 2]uint64
	MergeOutHist                    [maxGLRStacks + 2]uint64
	ForkActionsHist                 [8]uint64
	CloneTreeCalls                  uint64
	CloneTreePublicNodes            uint64
	CloneTreeFinalRefs              uint64
	CloneTreeCompactCopies          uint64
	CloneTreeChildRefs              uint64
	CloneOffsetCalls                uint64
	CloneOffsetPublicNodes          uint64
	CloneOffsetCopies               uint64
	CloneOffsetShifted              uint64
	NodeEditCalls                   uint64
	NodeEditNoopCalls               uint64
	NodeEditCompactRefs             uint64
	NodeEditShifted                 uint64
	NodeEditMarked                  uint64
	DenseMutationCalls              uint64
	DenseMutationDrains             uint64
	MutationChildRefCOW             uint64
}
