package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"

	"golang.org/x/sync/errgroup"
)

// RunBatchManifest clones each grammar repo in the manifest, extracts parser
// tables, and writes generated Go grammar files to outDir.
func RunBatchManifest(manifestPath, outDir, pkg string, compact bool) error {
	entries, err := ParseManifest(manifestPath)
	if err != nil {
		return fmt.Errorf("parse manifest: %w", err)
	}
	if len(entries) == 0 {
		return fmt.Errorf("manifest is empty: %s", manifestPath)
	}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("mkdir outdir: %w", err)
	}
	blobDir := filepath.Join(outDir, "grammar_blobs")
	if err := os.MkdirAll(blobDir, 0755); err != nil {
		return fmt.Errorf("mkdir blob dir: %w", err)
	}

	tmpRoot, err := os.MkdirTemp("", "ts2go-batch-*")
	if err != nil {
		return fmt.Errorf("mktemp: %w", err)
	}
	defer os.RemoveAll(tmpRoot)

	compactor := NewLanguageCompactor()
	loaderSpecs := make([]embeddedLoaderSpec, 0, len(entries))

	grp, grpCtx := errgroup.WithContext(context.Background())
	grp.SetLimit(runtime.GOMAXPROCS(-1))
	var mu sync.Mutex
	for _, entry := range entries {
		if err := grpCtx.Err(); err != nil {
			break
		}
		if grammargenOwnedBlobs[entry.Name] {
			// This language's checked-in blob is compiled by grammargen, not
			// ts2go. Keep the embedded loader entry pointing at the existing
			// blob but never re-extract it from C tables or emit a ts2go
			// register stub for it (its registry entry advertises
			// GrammarSourceGrammargenBlob).
			mu.Lock()
			loaderSpecs = append(loaderSpecs, embeddedLoaderSpec{
				Name:     entry.Name,
				BlobName: safeFileBase(entry.Name) + ".bin",
			})
			mu.Unlock()
			fmt.Printf("skipped %s (grammargen-owned blob; regenerate with: go run ./cmd/grammargen -lr-split -bin grammars/grammar_blobs/%s.bin %s)\n",
				entry.Name, safeFileBase(entry.Name), entry.Name)
			continue
		}
		grp.Go(func() error {
			if err := grpCtx.Err(); err != nil {
				return err
			}
			repoDir := filepath.Join(tmpRoot, safeFileBase(entry.Name))
			if err := cloneRepo(entry.RepoURL, entry.Commit, repoDir); err != nil {
				return fmt.Errorf("%s: clone: %w", entry.Name, err)
			}

			parserPath := filepath.Join(repoDir, entry.Subdir, "parser.c")
			if _, err := os.Stat(parserPath); err != nil {
				detected, derr := findParserC(repoDir)
				if derr != nil {
					return fmt.Errorf("%s: parser.c not found under %s", entry.Name, repoDir)
				}
				parserPath = detected
			}
			source, err := os.ReadFile(parserPath)
			if err != nil {
				return fmt.Errorf("%s: read %s: %w", entry.Name, parserPath, err)
			}

			grammar, err := ExtractGrammar(string(source))
			if err != nil {
				return fmt.Errorf("%s: extract: %w", entry.Name, err)
			}
			grammar.Name = entry.Name

			fileBase := safeFileBase(entry.Name)
			blobName := fileBase + ".bin"
			blobPath := filepath.Join(blobDir, blobName)

			lang := BuildLanguage(grammar)
			if compact {
				mu.Lock()
				compactor.CompactLanguage(lang)
				mu.Unlock()
			}
			blob, err := EncodeLanguageBlob(lang)
			if err != nil {
				return fmt.Errorf("%s: encode blob: %w", entry.Name, err)
			}
			if err := os.WriteFile(blobPath, blob, 0644); err != nil {
				return fmt.Errorf("%s: write %s: %w", entry.Name, blobPath, err)
			}

			mu.Lock()
			loaderSpecs = append(loaderSpecs, embeddedLoaderSpec{
				Name:     grammar.Name,
				BlobName: blobName,
			})
			mu.Unlock()

			highlightQuery, _ := loadHighlightQuery(repoDir)
			if err := writeRegisterStub(outDir, entry, highlightQuery); err != nil {
				return fmt.Errorf("%s: write register stub: %w", entry.Name, err)
			}

			fmt.Printf("generated %s (%d states, %d symbols)\n", blobPath, grammar.StateCount, grammar.SymbolCount)
			return nil
		})
	}
	if err := grp.Wait(); err != nil {
		return err
	}

	if err := removeLegacyLoaderFiles(outDir); err != nil {
		return fmt.Errorf("cleanup old loader stubs: %w", err)
	}
	outFile, err := writeEmbeddedLoaderAggregate(outDir, pkg, loaderSpecs)
	if err != nil {
		return fmt.Errorf("write embedded loader aggregate: %w", err)
	}
	fmt.Printf("generated %s (%d languages)\n", outFile, len(loaderSpecs))

	return nil
}

type embeddedLoaderSpec struct {
	Name     string
	BlobName string
}

func removeLegacyLoaderFiles(outDir string) error {
	matches, err := filepath.Glob(filepath.Join(outDir, "*_grammar_loader.go"))
	if err != nil {
		return err
	}
	for _, p := range matches {
		if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	return nil
}

func writeEmbeddedLoaderAggregate(outDir, pkg string, specs []embeddedLoaderSpec) (string, error) {
	sort.Slice(specs, func(i, j int) bool {
		return specs[i].Name < specs[j].Name
	})

	var b strings.Builder
	b.WriteString("// Code generated by ts2go batch. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import \"github.com/odvcencio/gotreesitter\"\n\n")

	for _, spec := range specs {
		funcName := languageFuncName(spec.Name)
		fmt.Fprintf(&b, "// %s returns the %s language definition.\n", funcName, spec.Name)
		fmt.Fprintf(&b, "func %s() *gotreesitter.Language {\n", funcName)
		fmt.Fprintf(&b, "\treturn loadEmbeddedLanguage(%q)\n", spec.BlobName)
		b.WriteString("}\n\n")
	}

	outFile := filepath.Join(outDir, "embedded_grammars_gen.go")
	if err := os.WriteFile(outFile, []byte(b.String()), 0644); err != nil {
		return "", err
	}
	return outFile, nil
}

func cloneRepo(repoURL, commit, dest string) error {
	cmd := exec.Command("git", "clone", "--depth=1", repoURL, dest)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%v: %s", err, strings.TrimSpace(string(out)))
	}
	if commit == "" {
		return nil
	}

	// Fast path: pinned commit is already available in shallow clone.
	cmd = exec.Command("git", "-C", dest, "checkout", "--detach", commit)
	out, err = cmd.CombinedOutput()
	if err == nil {
		return nil
	}

	// Fallback: fetch the exact pinned commit, then detach at FETCH_HEAD.
	cmd = exec.Command("git", "-C", dest, "fetch", "--depth=1", "origin", commit)
	out, err = cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("fetch commit %s: %v: %s", commit, err, strings.TrimSpace(string(out)))
	}
	cmd = exec.Command("git", "-C", dest, "checkout", "--detach", "FETCH_HEAD")
	out, err = cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("checkout commit %s: %v: %s", commit, err, strings.TrimSpace(string(out)))
	}
	return nil
}

func loadHighlightQuery(repoDir string) (string, bool) {
	candidates := []string{
		filepath.Join(repoDir, "queries", "highlights.scm"),
		filepath.Join(repoDir, "queries", "highlight.scm"),
	}
	for _, p := range candidates {
		b, err := os.ReadFile(p)
		if err == nil {
			return string(b), true
		}
	}
	return "", false
}

// grammargenOwnedBlobs lists languages whose checked-in grammar_blobs/*.bin
// is compiled by grammargen (go run ./cmd/grammargen -lr-split -bin ...)
// instead of the ts2go C-table extraction pipeline. Batch regeneration must
// not clobber these blobs or relabel their registry entries: they advertise
// GrammarSourceGrammargenBlob in grammars/registry_builtin_gen.go.
var grammargenOwnedBlobs = map[string]bool{
	"go": true,
}

func writeRegisterStub(outDir string, entry ManifestEntry, highlightQuery string) error {
	nameIdent := languageRegisterIdentifier(entry.Name)
	funcName := languageFuncName(entry.Name)

	var extList strings.Builder
	for i, ext := range entry.Extensions {
		if i > 0 {
			extList.WriteString(", ")
		}
		extList.WriteString(fmt.Sprintf("%q", ext))
	}
	extExpr := "nil"
	if extList.Len() > 0 {
		extExpr = "[]string{" + extList.String() + "}"
	}

	code := fmt.Sprintf(`// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           %q,
		Extensions:     %s,
		Language:       %s,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: %sHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory(%q),
	})
}

const %sHighlightQuery = %q
`, entry.Name, extExpr, funcName, nameIdent, entry.Name, nameIdent, highlightQuery)

	outFile := filepath.Join(outDir, safeFileBase(entry.Name)+"_register.go")
	return os.WriteFile(outFile, []byte(code), 0644)
}

func safeFileBase(s string) string {
	s = strings.TrimSpace(strings.ToLower(s))
	if s == "" {
		return "lang"
	}
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return strings.Trim(b.String(), "_")
}

func languageRegisterIdentifier(name string) string {
	id := toExportedIdentifier(name)
	if id == "" {
		id = "Lang"
	}
	return strings.ToLower(id[:1]) + id[1:]
}

func findParserC(repoDir string) (string, error) {
	var candidates []string
	err := filepath.WalkDir(repoDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			base := filepath.Base(path)
			if base == ".git" || base == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Name() == "parser.c" {
			candidates = append(candidates, path)
		}
		return nil
	})
	if err != nil {
		return "", err
	}
	if len(candidates) == 0 {
		return "", fmt.Errorf("parser.c not found")
	}
	for _, c := range candidates {
		if strings.Contains(c, string(filepath.Separator)+"src"+string(filepath.Separator)+"parser.c") {
			return c, nil
		}
	}
	return candidates[0], nil
}
