//go:build !grammar_subset

package grammars

import "github.com/odvcencio/gotreesitter"

// scanner_attachments.go — NOT generated by ts2go batch.
//
// This file registers hand-written external scanners and external lex-state
// tables by language name so loadEmbeddedLanguage can attach them lazily when
// a specific language is decoded.

func init() {
	attachments := map[string]gotreesitter.ExternalScanner{
		"python":     PythonExternalScanner{},
		"elixir":     ElixirExternalScanner{},
		"comment":    CommentExternalScanner{},
		"doxygen":    DoxygenExternalScanner{},
		"foam":       FoamExternalScanner{},
		"nginx":      NginxExternalScanner{},
		"nushell":    NushellExternalScanner{},
		"r":          RExternalScanner{},
		"xml":        XMLExternalScanner{},
		"yuck":       YuckExternalScanner{},
		"purescript": PurescriptExternalScanner{},
		"typst":      TypstExternalScanner{},
		// New hand-written scanners:
		"jsdoc":           JsdocExternalScanner{},
		"toml":            TomlExternalScanner{},
		"gleam":           GleamExternalScanner{},
		"scss":            ScssExternalScanner{},
		"css":             CssExternalScanner{},
		"erlang":          ErlangExternalScanner{},
		"sql":             SqlExternalScanner{},
		"dockerfile":      DockerfileExternalScanner{},
		"dart":            DartExternalScanner{},
		"kotlin":          KotlinExternalScanner{},
		"ocaml":           OcamlExternalScanner{},
		"wgsl":            WgslExternalScanner{},
		"tablegen":        TablegenExternalScanner{},
		"less":            LessExternalScanner{},
		"properties":      PropertiesExternalScanner{},
		"cooklang":        CooklangExternalScanner{},
		"dhall":           DhallExternalScanner{},
		"kdl":             KdlExternalScanner{},
		"editorconfig":    EditorconfigExternalScanner{},
		"janet":           JanetExternalScanner{},
		"cuda":            CudaExternalScanner{},
		"arduino":         ArduinoExternalScanner{},
		"hlsl":            HlslExternalScanner{},
		"jsonnet":         JsonnetExternalScanner{},
		"tcl":             TclExternalScanner{},
		"bicep":           BicepExternalScanner{},
		"ron":             RonExternalScanner{},
		"beancount":       BeancountExternalScanner{},
		"dtd":             DtdExternalScanner{},
		"nix":             NixExternalScanner{},
		"luau":            LuauExternalScanner{},
		"liquid":          LiquidExternalScanner{},
		"wolfram":         WolframExternalScanner{},
		"squirrel":        SquirrelExternalScanner{},
		"uxntal":          UxntalExternalScanner{},
		"gn":              GnExternalScanner{},
		"godot_resource":  GodotResourceExternalScanner{},
		"kconfig":         KconfigExternalScanner{},
		"haxe":            HaxeExternalScanner{},
		"fish":            FishExternalScanner{},
		"cue":             CueExternalScanner{},
		"powershell":      PowershellExternalScanner{},
		"racket":          RacketExternalScanner{},
		"earthfile":       EarthfileExternalScanner{},
		"awk":             AwkExternalScanner{},
		"firrtl":          FirrtlExternalScanner{},
		"just":            JustExternalScanner{},
		"cairo":           CairoExternalScanner{},
		"gitcommit":       GitcommitExternalScanner{},
		"cmake":           CmakeExternalScanner{},
		"teal":            TealExternalScanner{},
		"templ":           TemplExternalScanner{},
		"org":             OrgExternalScanner{},
		"odin":            OdinExternalScanner{},
		"tsx":             TsxExternalScanner{},
		"d":               DExternalScanner{},
		"nickel":          NickelExternalScanner{},
		"pug":             PugExternalScanner{},
		"agda":            AgdaExternalScanner{},
		"fennel":          FennelExternalScanner{},
		"cobol":           CobolExternalScanner{},
		"hack":            HackExternalScanner{},
		"starlark":        StarlarkExternalScanner{},
		"julia":           JuliaExternalScanner{},
		"pkl":             PklExternalScanner{},
		"c_sharp":         CSharpExternalScanner{},
		"mojo":            MojoExternalScanner{},
		"blade":           BladeExternalScanner{},
		"angular":         AngularExternalScanner{},
		"vue":             VueExternalScanner{},
		"astro":           AstroExternalScanner{},
		"gdscript":        GdscriptExternalScanner{},
		"elm":             ElmExternalScanner{},
		"disassembly":     DisassemblyExternalScanner{},
		"norg":            NorgExternalScanner{},
		"bitbake":         BitbakeExternalScanner{},
		"scala":           ScalaExternalScanner{},
		"php":             PhpExternalScanner{},
		"fsharp":          FsharpExternalScanner{},
		"fortran":         FortranExternalScanner{},
		"markdown_inline": MarkdownInlineExternalScanner{},
		"matlab":          MatlabExternalScanner{},
		"tlaplus":         TlaplusExternalScanner{},
		"markdown":        MarkdownExternalScanner{},
		"nim":             NimExternalScanner{},
		"bash":            BashExternalScanner{},
		"ruby":            RubyExternalScanner{},
		"swift":           SwiftExternalScanner{},
		"perl":            PerlExternalScanner{},
		"crystal":         CrystalExternalScanner{},
		"djot":            DjotExternalScanner{},
		"cpp":             CppExternalScanner{},
		"caddy":           CaddyExternalScanner{},
		"javascript":      JavaScriptExternalScanner{},
		"typescript":      TypeScriptExternalScanner{},
		"rust":            RustExternalScanner{},
		"hcl":             HclExternalScanner{},
		"rescript":        RescriptExternalScanner{},
		"svelte":          SvelteExternalScanner{},
		"rst":             RstExternalScanner{},
		"haskell":         HaskellExternalScanner{},
		"vhdl":            VhdlExternalScanner{},
		"html":            HTMLExternalScanner{},
		"yaml":            YamlExternalScanner{},
	}

	// External lex states tables extracted from ts_external_scanner_states
	// in each grammar's parser.c. These provide precise external token
	// validity per parser state, matching C tree-sitter behavior.
	externalLexStates := map[string][][]bool{
		// Bash: generated from tree-sitter-bash ts_external_scanner_states.
		"bash": bashExternalLexStates,
		// SCSS: 6 external lex states, 4 external tokens
		// [0]=_descendant_operator [1]=_pseudo_class_selector_colon
		// [2]=__error_recovery [3]=_concat
		"scss": {
			{false, false, false, false}, // state 0: no external tokens
			{true, true, true, true},     // state 1: all tokens
			{false, true, false, false},  // state 2: colon only
			{true, true, false, true},    // state 3: desc_op, colon, concat
			{true, true, false, false},   // state 4: desc_op, colon
			{false, false, false, true},  // state 5: concat only
		},
		// YAML: generated from tree-sitter-yaml ts_external_scanner_states.
		"yaml": yamlExternalLexStates,
		// Python: generated from tree-sitter-python ts_external_scanner_states.
		"python": pythonExternalLexStates,
	}

	// Register scanners in the embedded loader's registry so direct calls like
	// JavascriptLanguage() get external scanners attached at decode time.
	for name, s := range attachments {
		RegisterExternalScanner(name, s)
	}
	for name, els := range externalLexStates {
		RegisterExternalLexStates(name, els)
	}
}
