// Command gen_subset_blob_embeds generates the per-language
// z_subset_blob_embed_<lang>.go files that power embedded grammar_subset builds
// (issue #88: per-language compile-time grammar selection).
//
// Each generated file embeds exactly one grammar blob behind the
// `grammar_subset_<lang>` build tag and registers it with the subset blob
// source (blob_source_subset_embedded.go). Building with, e.g.,
//
//	go build -tags 'grammar_subset grammar_subset_go grammar_subset_python'
//
// then embeds only go.bin + python.bin into the binary instead of all ~206
// blobs — the whole point of the feature.
//
// The generated set must stay in sync with grammars/grammar_blobs/*.bin. Run
// from the repo root after adding/removing a grammar blob:
//
//	go run ./cmd/gen_subset_blob_embeds
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	blobDir = "grammars/grammar_blobs"
	outDir  = "grammars"
	prefix  = "z_subset_blob_embed_"
)

// fileTmpl: %[1]s is the language name (a valid Go identifier suffix).
const fileTmpl = `//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_%[1]s

// Code generated by cmd/gen_subset_blob_embeds. DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/%[1]s.bin
var subsetBlobFS_%[1]s embed.FS

func init() { registerSubsetEmbeddedBlob("%[1]s.bin", subsetBlobFS_%[1]s) }
`

var identRE = regexp.MustCompile(`^[a-z0-9_]+$`)

func main() {
	entries, err := os.ReadDir(blobDir)
	if err != nil {
		fail(err)
	}
	var langs []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".bin") {
			continue
		}
		lang := strings.TrimSuffix(name, ".bin")
		if !identRE.MatchString(lang) {
			fail(fmt.Errorf("blob %q yields invalid build-tag/identifier suffix %q", name, lang))
		}
		langs = append(langs, lang)
	}
	sort.Strings(langs)

	// Remove stale generated files (blobs that no longer exist).
	existing, _ := filepath.Glob(filepath.Join(outDir, prefix+"*.go"))
	want := make(map[string]bool, len(langs))
	for _, l := range langs {
		want[filepath.Join(outDir, prefix+l+".go")] = true
	}
	for _, f := range existing {
		if !want[f] {
			if err := os.Remove(f); err != nil {
				fail(err)
			}
			fmt.Printf("removed stale %s\n", f)
		}
	}

	for _, lang := range langs {
		out := filepath.Join(outDir, prefix+lang+".go")
		if err := os.WriteFile(out, []byte(fmt.Sprintf(fileTmpl, lang)), 0o644); err != nil {
			fail(err)
		}
	}
	fmt.Printf("generated %d %s<lang>.go files\n", len(langs), prefix)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen_subset_blob_embeds:", err)
	os.Exit(1)
}
