package grammargen

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// EmitGrammarGo takes a Grammar IR and emits Go source code that reconstructs
// it using grammargen DSL calls. The output is a standalone Go file in the given
// package with a function of the given name that returns *Grammar.
func EmitGrammarGo(g *Grammar, pkgName, funcName string) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	fmt.Fprintf(&buf, "// %s returns the %s grammar.\n", funcName, g.Name)
	fmt.Fprintf(&buf, "// Code generated by EmitGrammarGo. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "func %s() *Grammar {\n", funcName)
	fmt.Fprintf(&buf, "\tg := NewGrammar(%s)\n\n", goString(g.Name))

	// Emit rules in order.
	for _, name := range g.RuleOrder {
		rule := g.Rules[name]
		fmt.Fprintf(&buf, "\tg.Define(%s,\n", goString(name))
		emitRule(&buf, rule, 2)
		fmt.Fprintf(&buf, "\t)\n\n")
	}

	// Emit extras.
	if len(g.Extras) > 0 {
		fmt.Fprintf(&buf, "\tg.SetExtras(\n")
		for _, extra := range g.Extras {
			emitRule(&buf, extra, 2)
			fmt.Fprintf(&buf, ",\n")
		}
		fmt.Fprintf(&buf, "\t)\n\n")
	}

	// Emit conflicts.
	if len(g.Conflicts) > 0 {
		fmt.Fprintf(&buf, "\tg.SetConflicts(\n")
		for _, conflict := range g.Conflicts {
			fmt.Fprintf(&buf, "\t\t[]string{")
			for i, name := range conflict {
				if i > 0 {
					fmt.Fprintf(&buf, ", ")
				}
				fmt.Fprintf(&buf, "%s", goString(name))
			}
			fmt.Fprintf(&buf, "},\n")
		}
		fmt.Fprintf(&buf, "\t)\n\n")
	}

	// Emit externals.
	if len(g.Externals) > 0 {
		fmt.Fprintf(&buf, "\tg.SetExternals(\n")
		for _, ext := range g.Externals {
			emitRule(&buf, ext, 2)
			fmt.Fprintf(&buf, ",\n")
		}
		fmt.Fprintf(&buf, "\t)\n\n")
	}

	// Emit inline.
	if len(g.Inline) > 0 {
		fmt.Fprintf(&buf, "\tg.SetInline(")
		for i, name := range g.Inline {
			if i > 0 {
				fmt.Fprintf(&buf, ", ")
			}
			fmt.Fprintf(&buf, "%s", goString(name))
		}
		fmt.Fprintf(&buf, ")\n\n")
	}

	// Emit word.
	if g.Word != "" {
		fmt.Fprintf(&buf, "\tg.SetWord(%s)\n\n", goString(g.Word))
	}

	// Emit supertypes.
	if len(g.Supertypes) > 0 {
		fmt.Fprintf(&buf, "\tg.SetSupertypes(")
		for i, name := range g.Supertypes {
			if i > 0 {
				fmt.Fprintf(&buf, ", ")
			}
			fmt.Fprintf(&buf, "%s", goString(name))
		}
		fmt.Fprintf(&buf, ")\n\n")
	}

	// Emit reserved word sets.
	if len(g.ReservedWordSets) > 0 {
		fmt.Fprintf(&buf, "\tg.ReservedWordSets = []ReservedWordSet{\n")
		for _, set := range g.ReservedWordSets {
			fmt.Fprintf(&buf, "\t\t{\n")
			fmt.Fprintf(&buf, "\t\t\tName: %s,\n", goString(set.Name))
			if len(set.Rules) > 0 {
				fmt.Fprintf(&buf, "\t\t\tRules: []*Rule{\n")
				for _, rule := range set.Rules {
					emitRule(&buf, rule, 4)
					fmt.Fprintf(&buf, ",\n")
				}
				fmt.Fprintf(&buf, "\t\t\t},\n")
			}
			fmt.Fprintf(&buf, "\t\t},\n")
		}
		fmt.Fprintf(&buf, "\t}\n\n")
	}

	// Emit precedence levels.
	if len(g.Precedences) > 0 {
		fmt.Fprintf(&buf, "\tg.Precedences = [][]PrecEntry{\n")
		for _, level := range g.Precedences {
			fmt.Fprintf(&buf, "\t\t{\n")
			for _, entry := range level {
				if entry.IsSymbol {
					fmt.Fprintf(&buf, "\t\t\t{IsSymbol: true, Name: %s},\n", goString(entry.Name))
				} else {
					fmt.Fprintf(&buf, "\t\t\t{Name: %s},\n", goString(entry.Name))
				}
			}
			fmt.Fprintf(&buf, "\t\t},\n")
		}
		fmt.Fprintf(&buf, "\t}\n\n")
	}

	// Emit EnableLRSplitting.
	if g.EnableLRSplitting {
		fmt.Fprintf(&buf, "\tg.EnableLRSplitting = true\n\n")
	}

	// Emit BinaryRepeatMode.
	if g.BinaryRepeatMode {
		fmt.Fprintf(&buf, "\tg.BinaryRepeatMode = true\n\n")
	}

	if g.PreserveKeywordIdentifierConflicts {
		fmt.Fprintf(&buf, "\tg.PreserveKeywordIdentifierConflicts = true\n\n")
	}

	if g.ChoiceLiftThreshold != 0 {
		fmt.Fprintf(&buf, "\tg.ChoiceLiftThreshold = %d\n\n", g.ChoiceLiftThreshold)
	}

	if len(g.Tests) > 0 {
		for _, tc := range g.Tests {
			if tc.ExpectError {
				fmt.Fprintf(&buf, "\tg.TestError(%s, %s)\n", goString(tc.Name), goString(tc.Input))
				continue
			}
			fmt.Fprintf(&buf, "\tg.Test(%s, %s, %s)\n", goString(tc.Name), goString(tc.Input), goString(tc.Expected))
		}
		fmt.Fprintf(&buf, "\n")
	}

	fmt.Fprintf(&buf, "\treturn g\n")
	fmt.Fprintf(&buf, "}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted source with error context for debugging.
		return buf.Bytes(), fmt.Errorf("gofmt: %w\n%s", err, buf.Bytes())
	}
	return formatted, nil
}

// emitRule writes the Go code for a single Rule node at the given indent level.
func emitRule(buf *bytes.Buffer, r *Rule, indent int) {
	tabs := strings.Repeat("\t", indent)

	if r == nil {
		fmt.Fprintf(buf, "%sBlank()", tabs)
		return
	}

	switch r.Kind {
	case RuleBlank:
		fmt.Fprintf(buf, "%sBlank()", tabs)

	case RuleString:
		fmt.Fprintf(buf, "%sStr(%s)", tabs, goString(r.Value))

	case RulePattern:
		fmt.Fprintf(buf, "%sPat(%s)", tabs, goPattern(r.Value))

	case RuleSymbol:
		fmt.Fprintf(buf, "%sSym(%s)", tabs, goString(r.Value))

	case RuleSeq:
		fmt.Fprintf(buf, "%sSeq(\n", tabs)
		for _, child := range r.Children {
			emitRule(buf, child, indent+1)
			fmt.Fprintf(buf, ",\n")
		}
		fmt.Fprintf(buf, "%s)", tabs)

	case RuleChoice:
		fmt.Fprintf(buf, "%sChoice(\n", tabs)
		for _, child := range r.Children {
			emitRule(buf, child, indent+1)
			fmt.Fprintf(buf, ",\n")
		}
		fmt.Fprintf(buf, "%s)", tabs)

	case RuleRepeat:
		if len(r.Children) == 1 {
			fmt.Fprintf(buf, "%sRepeat(\n", tabs)
			emitRule(buf, r.Children[0], indent+1)
			fmt.Fprintf(buf, ",\n")
			fmt.Fprintf(buf, "%s)", tabs)
		}

	case RuleRepeat1:
		if len(r.Children) == 1 {
			fmt.Fprintf(buf, "%sRepeat1(\n", tabs)
			emitRule(buf, r.Children[0], indent+1)
			fmt.Fprintf(buf, ",\n")
			fmt.Fprintf(buf, "%s)", tabs)
		}

	case RuleOptional:
		if len(r.Children) == 1 {
			fmt.Fprintf(buf, "%sOptional(\n", tabs)
			emitRule(buf, r.Children[0], indent+1)
			fmt.Fprintf(buf, ",\n")
			fmt.Fprintf(buf, "%s)", tabs)
		}

	case RuleToken:
		if len(r.Children) == 1 {
			fmt.Fprintf(buf, "%sToken(\n", tabs)
			emitRule(buf, r.Children[0], indent+1)
			fmt.Fprintf(buf, ",\n")
			fmt.Fprintf(buf, "%s)", tabs)
		}

	case RuleImmToken:
		if len(r.Children) == 1 {
			fmt.Fprintf(buf, "%sImmToken(\n", tabs)
			emitRule(buf, r.Children[0], indent+1)
			fmt.Fprintf(buf, ",\n")
			fmt.Fprintf(buf, "%s)", tabs)
		}

	case RuleField:
		if len(r.Children) == 1 {
			fmt.Fprintf(buf, "%sField(%s,\n", tabs, goString(r.Value))
			emitRule(buf, r.Children[0], indent+1)
			fmt.Fprintf(buf, ",\n")
			fmt.Fprintf(buf, "%s)", tabs)
		}

	case RulePrec:
		if len(r.Children) == 1 {
			fmt.Fprintf(buf, "%sPrec(%d,\n", tabs, r.Prec)
			emitRule(buf, r.Children[0], indent+1)
			fmt.Fprintf(buf, ",\n")
			fmt.Fprintf(buf, "%s)", tabs)
		}

	case RulePrecLeft:
		if len(r.Children) == 1 {
			fmt.Fprintf(buf, "%sPrecLeft(%d,\n", tabs, r.Prec)
			emitRule(buf, r.Children[0], indent+1)
			fmt.Fprintf(buf, ",\n")
			fmt.Fprintf(buf, "%s)", tabs)
		}

	case RulePrecRight:
		if len(r.Children) == 1 {
			fmt.Fprintf(buf, "%sPrecRight(%d,\n", tabs, r.Prec)
			emitRule(buf, r.Children[0], indent+1)
			fmt.Fprintf(buf, ",\n")
			fmt.Fprintf(buf, "%s)", tabs)
		}

	case RulePrecDynamic:
		if len(r.Children) == 1 {
			fmt.Fprintf(buf, "%sPrecDynamic(%d,\n", tabs, r.Prec)
			emitRule(buf, r.Children[0], indent+1)
			fmt.Fprintf(buf, ",\n")
			fmt.Fprintf(buf, "%s)", tabs)
		}

	case RuleAlias:
		if len(r.Children) == 1 {
			fmt.Fprintf(buf, "%sAlias(\n", tabs)
			emitRule(buf, r.Children[0], indent+1)
			fmt.Fprintf(buf, ",\n")
			fmt.Fprintf(buf, "%s\t%s, %t,\n", tabs, goString(r.Value), r.Named)
			fmt.Fprintf(buf, "%s)", tabs)
		}
	}
}

// goString returns a Go string literal for the given string.
func goString(s string) string {
	return strconv.Quote(s)
}

// goPattern returns a Go string literal for a regex pattern.
// Uses backtick quoting when the pattern contains no backticks or newlines.
func goPattern(s string) string {
	if !strings.Contains(s, "`") && !strings.Contains(s, "\n") {
		return "`" + s + "`"
	}
	return strconv.Quote(s)
}
