package grammargen

// TSXGrammar returns the tsx grammar.
// Code generated by EmitGrammarGo. DO NOT EDIT.
func TSXGrammar() *Grammar {
	g := NewGrammar("tsx")

	g.Define("program",
		Seq(
			Choice(
				Sym("hash_bang_line"),
				Blank(),
			),
			Repeat(
				Sym("statement"),
			),
		))

	g.Define("hash_bang_line",
		Pat(`#!.*`))

	g.Define("export_statement",
		Choice(
			Choice(
				Seq(
					Str("export"),
					Choice(
						Seq(
							Str("*"),
							Sym("_from_clause"),
						),
						Seq(
							Sym("namespace_export"),
							Sym("_from_clause"),
						),
						Seq(
							Sym("export_clause"),
							Sym("_from_clause"),
						),
						Sym("export_clause"),
					),
					Sym("_semicolon"),
				),
				Seq(
					Repeat(
						Field("decorator",
							Sym("decorator"),
						),
					),
					Str("export"),
					Choice(
						Field("declaration",
							Sym("declaration"),
						),
						Seq(
							Str("default"),
							Choice(
								Field("declaration",
									Sym("declaration"),
								),
								Seq(
									Field("value",
										Sym("expression"),
									),
									Sym("_semicolon"),
								),
							),
						),
					),
				),
			),
			Seq(
				Str("export"),
				Str("type"),
				Sym("export_clause"),
				Choice(
					Sym("_from_clause"),
					Blank(),
				),
				Sym("_semicolon"),
			),
			Seq(
				Str("export"),
				Str("="),
				Sym("expression"),
				Sym("_semicolon"),
			),
			Seq(
				Str("export"),
				Str("as"),
				Str("namespace"),
				Sym("identifier"),
				Sym("_semicolon"),
			),
		))

	g.Define("namespace_export",
		Seq(
			Str("*"),
			Str("as"),
			Sym("_module_export_name"),
		))

	g.Define("export_clause",
		Seq(
			Str("{"),
			Choice(
				Seq(
					Sym("export_specifier"),
					Repeat(
						Seq(
							Str(","),
							Sym("export_specifier"),
						),
					),
				),
				Blank(),
			),
			Choice(
				Str(","),
				Blank(),
			),
			Str("}"),
		))

	g.Define("export_specifier",
		Seq(
			Choice(
				Choice(
					Str("type"),
					Str("typeof"),
				),
				Blank(),
			),
			Seq(
				Field("name",
					Sym("_module_export_name"),
				),
				Choice(
					Seq(
						Str("as"),
						Field("alias",
							Sym("_module_export_name"),
						),
					),
					Blank(),
				),
			),
		))

	g.Define("_module_export_name",
		Choice(
			Sym("identifier"),
			Sym("string"),
		))

	g.Define("declaration",
		Choice(
			Choice(
				Sym("function_declaration"),
				Sym("generator_function_declaration"),
				Sym("class_declaration"),
				Sym("lexical_declaration"),
				Sym("variable_declaration"),
			),
			Sym("function_signature"),
			Sym("abstract_class_declaration"),
			Sym("module"),
			Prec(13,
				Sym("internal_module"),
			),
			Sym("type_alias_declaration"),
			Sym("enum_declaration"),
			Sym("interface_declaration"),
			Sym("import_alias"),
			Sym("ambient_declaration"),
		))

	g.Define("import",
		Token(
			Str("import"),
		))

	g.Define("import_statement",
		Seq(
			Str("import"),
			Choice(
				Choice(
					Str("type"),
					Str("typeof"),
				),
				Blank(),
			),
			Choice(
				Seq(
					Sym("import_clause"),
					Sym("_from_clause"),
				),
				Sym("import_require_clause"),
				Field("source",
					Sym("string"),
				),
			),
			Choice(
				Sym("import_attribute"),
				Blank(),
			),
			Sym("_semicolon"),
		))

	g.Define("import_clause",
		Choice(
			Sym("namespace_import"),
			Sym("named_imports"),
			Seq(
				Sym("_import_identifier"),
				Choice(
					Seq(
						Str(","),
						Choice(
							Sym("namespace_import"),
							Sym("named_imports"),
						),
					),
					Blank(),
				),
			),
		))

	g.Define("_from_clause",
		Seq(
			Str("from"),
			Field("source",
				Sym("string"),
			),
		))

	g.Define("namespace_import",
		Seq(
			Str("*"),
			Str("as"),
			Sym("identifier"),
		))

	g.Define("named_imports",
		Seq(
			Str("{"),
			Choice(
				Seq(
					Sym("import_specifier"),
					Repeat(
						Seq(
							Str(","),
							Sym("import_specifier"),
						),
					),
				),
				Blank(),
			),
			Choice(
				Str(","),
				Blank(),
			),
			Str("}"),
		))

	g.Define("import_specifier",
		Seq(
			Choice(
				Choice(
					Str("type"),
					Str("typeof"),
				),
				Blank(),
			),
			Choice(
				Field("name",
					Sym("_import_identifier"),
				),
				Seq(
					Field("name",
						Choice(
							Sym("_module_export_name"),
							Alias(
								Str("type"),
								"identifier", true,
							),
						),
					),
					Str("as"),
					Field("alias",
						Sym("_import_identifier"),
					),
				),
			),
		))

	g.Define("import_attribute",
		Seq(
			Choice(
				Str("with"),
				Str("assert"),
			),
			Sym("object"),
		))

	g.Define("statement",
		Choice(
			Sym("export_statement"),
			Sym("import_statement"),
			Sym("debugger_statement"),
			Sym("expression_statement"),
			Sym("declaration"),
			Sym("statement_block"),
			Sym("if_statement"),
			Sym("switch_statement"),
			Sym("for_statement"),
			Sym("for_in_statement"),
			Sym("while_statement"),
			Sym("do_statement"),
			Sym("try_statement"),
			Sym("with_statement"),
			Sym("break_statement"),
			Sym("continue_statement"),
			Sym("return_statement"),
			Sym("throw_statement"),
			Sym("empty_statement"),
			Sym("labeled_statement"),
		))

	g.Define("expression_statement",
		Seq(
			Sym("_expressions"),
			Sym("_semicolon"),
		))

	g.Define("variable_declaration",
		Seq(
			Str("var"),
			Seq(
				Sym("variable_declarator"),
				Repeat(
					Seq(
						Str(","),
						Sym("variable_declarator"),
					),
				),
			),
			Sym("_semicolon"),
		))

	g.Define("lexical_declaration",
		Seq(
			Field("kind",
				Choice(
					Str("let"),
					Str("const"),
				),
			),
			Seq(
				Sym("variable_declarator"),
				Repeat(
					Seq(
						Str(","),
						Sym("variable_declarator"),
					),
				),
			),
			Sym("_semicolon"),
		))

	g.Define("variable_declarator",
		Choice(
			Seq(
				Field("name",
					Choice(
						Sym("identifier"),
						Sym("_destructuring_pattern"),
					),
				),
				Field("type",
					Choice(
						Sym("type_annotation"),
						Blank(),
					),
				),
				Choice(
					Sym("_initializer"),
					Blank(),
				),
			),
			Prec(13,
				Seq(
					Field("name",
						Sym("identifier"),
					),
					Str("!"),
					Field("type",
						Sym("type_annotation"),
					),
				),
			),
		))

	g.Define("statement_block",
		PrecRight(0,
			Seq(
				Str("{"),
				Repeat(
					Sym("statement"),
				),
				Str("}"),
				Choice(
					Sym("_automatic_semicolon"),
					Blank(),
				),
			),
		))

	g.Define("else_clause",
		Seq(
			Str("else"),
			Sym("statement"),
		))

	g.Define("if_statement",
		PrecRight(0,
			Seq(
				Str("if"),
				Field("condition",
					Sym("parenthesized_expression"),
				),
				Field("consequence",
					Sym("statement"),
				),
				Choice(
					Field("alternative",
						Sym("else_clause"),
					),
					Blank(),
				),
			),
		))

	g.Define("switch_statement",
		Seq(
			Str("switch"),
			Field("value",
				Sym("parenthesized_expression"),
			),
			Field("body",
				Sym("switch_body"),
			),
		))

	g.Define("for_statement",
		Seq(
			Str("for"),
			Str("("),
			Choice(
				Field("initializer",
					Choice(
						Sym("lexical_declaration"),
						Sym("variable_declaration"),
					),
				),
				Seq(
					Field("initializer",
						Sym("_expressions"),
					),
					Str(";"),
				),
				Field("initializer",
					Sym("empty_statement"),
				),
			),
			Field("condition",
				Choice(
					Seq(
						Sym("_expressions"),
						Str(";"),
					),
					Sym("empty_statement"),
				),
			),
			Field("increment",
				Choice(
					Sym("_expressions"),
					Blank(),
				),
			),
			Str(")"),
			Field("body",
				Sym("statement"),
			),
		))

	g.Define("for_in_statement",
		Seq(
			Str("for"),
			Choice(
				Str("await"),
				Blank(),
			),
			Sym("_for_header"),
			Field("body",
				Sym("statement"),
			),
		))

	g.Define("_for_header",
		Seq(
			Str("("),
			Choice(
				Field("left",
					Choice(
						Sym("_lhs_expression"),
						Sym("parenthesized_expression"),
					),
				),
				Seq(
					Field("kind",
						Str("var"),
					),
					Field("left",
						Choice(
							Sym("identifier"),
							Sym("_destructuring_pattern"),
						),
					),
					Choice(
						Sym("_initializer"),
						Blank(),
					),
				),
				Seq(
					Field("kind",
						Choice(
							Str("let"),
							Str("const"),
						),
					),
					Field("left",
						Choice(
							Sym("identifier"),
							Sym("_destructuring_pattern"),
						),
					),
					Choice(
						Sym("_automatic_semicolon"),
						Blank(),
					),
				),
			),
			Field("operator",
				Choice(
					Str("in"),
					Str("of"),
				),
			),
			Field("right",
				Sym("_expressions"),
			),
			Str(")"),
		))

	g.Define("while_statement",
		Seq(
			Str("while"),
			Field("condition",
				Sym("parenthesized_expression"),
			),
			Field("body",
				Sym("statement"),
			),
		))

	g.Define("do_statement",
		PrecRight(0,
			Seq(
				Str("do"),
				Field("body",
					Sym("statement"),
				),
				Str("while"),
				Field("condition",
					Sym("parenthesized_expression"),
				),
				Choice(
					Sym("_semicolon"),
					Blank(),
				),
			),
		))

	g.Define("try_statement",
		Seq(
			Str("try"),
			Field("body",
				Sym("statement_block"),
			),
			Choice(
				Field("handler",
					Sym("catch_clause"),
				),
				Blank(),
			),
			Choice(
				Field("finalizer",
					Sym("finally_clause"),
				),
				Blank(),
			),
		))

	g.Define("with_statement",
		Seq(
			Str("with"),
			Field("object",
				Sym("parenthesized_expression"),
			),
			Field("body",
				Sym("statement"),
			),
		))

	g.Define("break_statement",
		Seq(
			Str("break"),
			Field("label",
				Choice(
					Alias(
						Sym("identifier"),
						"statement_identifier", true,
					),
					Blank(),
				),
			),
			Sym("_semicolon"),
		))

	g.Define("continue_statement",
		Seq(
			Str("continue"),
			Field("label",
				Choice(
					Alias(
						Sym("identifier"),
						"statement_identifier", true,
					),
					Blank(),
				),
			),
			Sym("_semicolon"),
		))

	g.Define("debugger_statement",
		Seq(
			Str("debugger"),
			Sym("_semicolon"),
		))

	g.Define("return_statement",
		Seq(
			Str("return"),
			Choice(
				Sym("_expressions"),
				Blank(),
			),
			Sym("_semicolon"),
		))

	g.Define("throw_statement",
		Seq(
			Str("throw"),
			Sym("_expressions"),
			Sym("_semicolon"),
		))

	g.Define("empty_statement",
		Str(";"))

	g.Define("labeled_statement",
		PrecDynamic(-1,
			Seq(
				Field("label",
					Alias(
						Choice(
							Sym("identifier"),
							Sym("_reserved_identifier"),
						),
						"statement_identifier", true,
					),
				),
				Str(":"),
				Field("body",
					Sym("statement"),
				),
			),
		))

	g.Define("switch_body",
		Seq(
			Str("{"),
			Repeat(
				Choice(
					Sym("switch_case"),
					Sym("switch_default"),
				),
			),
			Str("}"),
		))

	g.Define("switch_case",
		Seq(
			Str("case"),
			Field("value",
				Sym("_expressions"),
			),
			Str(":"),
			Field("body",
				Repeat(
					Sym("statement"),
				),
			),
		))

	g.Define("switch_default",
		Seq(
			Str("default"),
			Str(":"),
			Field("body",
				Repeat(
					Sym("statement"),
				),
			),
		))

	g.Define("catch_clause",
		Seq(
			Str("catch"),
			Choice(
				Seq(
					Str("("),
					Field("parameter",
						Choice(
							Sym("identifier"),
							Sym("_destructuring_pattern"),
						),
					),
					Choice(
						Field("type",
							Sym("type_annotation"),
						),
						Blank(),
					),
					Str(")"),
				),
				Blank(),
			),
			Field("body",
				Sym("statement_block"),
			),
		))

	g.Define("finally_clause",
		Seq(
			Str("finally"),
			Field("body",
				Sym("statement_block"),
			),
		))

	g.Define("parenthesized_expression",
		Seq(
			Str("("),
			Choice(
				Seq(
					Sym("expression"),
					Field("type",
						Choice(
							Sym("type_annotation"),
							Blank(),
						),
					),
				),
				Sym("sequence_expression"),
			),
			Str(")"),
		))

	g.Define("_expressions",
		Choice(
			Sym("expression"),
			Sym("sequence_expression"),
		))

	g.Define("expression",
		Choice(
			Sym("as_expression"),
			Sym("satisfies_expression"),
			Sym("instantiation_expression"),
			Sym("internal_module"),
			Sym("primary_expression"),
			Sym("_jsx_element"),
			Sym("assignment_expression"),
			Sym("augmented_assignment_expression"),
			Sym("await_expression"),
			Sym("unary_expression"),
			Sym("binary_expression"),
			Sym("ternary_expression"),
			Sym("update_expression"),
			Sym("new_expression"),
			Sym("yield_expression"),
		))

	g.Define("primary_expression",
		Choice(
			Choice(
				Sym("subscript_expression"),
				Sym("member_expression"),
				Sym("parenthesized_expression"),
				Sym("_identifier"),
				Alias(
					Sym("_reserved_identifier"),
					"identifier", true,
				),
				Sym("this"),
				Sym("super"),
				Sym("number"),
				Sym("string"),
				Sym("template_string"),
				Sym("regex"),
				Sym("true"),
				Sym("false"),
				Sym("null"),
				Sym("object"),
				Sym("array"),
				Sym("function_expression"),
				Sym("arrow_function"),
				Sym("generator_function"),
				Sym("class"),
				Sym("meta_property"),
				Sym("call_expression"),
			),
			Sym("non_null_expression"),
		))

	g.Define("yield_expression",
		PrecRight(0,
			Seq(
				Str("yield"),
				Choice(
					Seq(
						Str("*"),
						Sym("expression"),
					),
					Choice(
						Sym("expression"),
						Blank(),
					),
				),
			),
		))

	g.Define("object",
		Prec(11,
			Seq(
				Str("{"),
				Choice(
					Seq(
						Choice(
							Choice(
								Sym("pair"),
								Sym("spread_element"),
								Sym("method_definition"),
								Alias(
									Choice(
										Sym("identifier"),
										Sym("_reserved_identifier"),
									),
									"shorthand_property_identifier", true,
								),
							),
							Blank(),
						),
						Repeat(
							Seq(
								Str(","),
								Choice(
									Choice(
										Sym("pair"),
										Sym("spread_element"),
										Sym("method_definition"),
										Alias(
											Choice(
												Sym("identifier"),
												Sym("_reserved_identifier"),
											),
											"shorthand_property_identifier", true,
										),
									),
									Blank(),
								),
							),
						),
					),
					Blank(),
				),
				Str("}"),
			),
		))

	g.Define("object_pattern",
		Prec(11,
			Seq(
				Str("{"),
				Choice(
					Seq(
						Choice(
							Choice(
								Sym("pair_pattern"),
								Sym("rest_pattern"),
								Sym("object_assignment_pattern"),
								Alias(
									Choice(
										Sym("identifier"),
										Sym("_reserved_identifier"),
									),
									"shorthand_property_identifier_pattern", true,
								),
							),
							Blank(),
						),
						Repeat(
							Seq(
								Str(","),
								Choice(
									Choice(
										Sym("pair_pattern"),
										Sym("rest_pattern"),
										Sym("object_assignment_pattern"),
										Alias(
											Choice(
												Sym("identifier"),
												Sym("_reserved_identifier"),
											),
											"shorthand_property_identifier_pattern", true,
										),
									),
									Blank(),
								),
							),
						),
					),
					Blank(),
				),
				Str("}"),
			),
		))

	g.Define("assignment_pattern",
		Seq(
			Field("left",
				Sym("pattern"),
			),
			Str("="),
			Field("right",
				Sym("expression"),
			),
		))

	g.Define("object_assignment_pattern",
		Seq(
			Field("left",
				Choice(
					Alias(
						Choice(
							Sym("_reserved_identifier"),
							Sym("identifier"),
						),
						"shorthand_property_identifier_pattern", true,
					),
					Sym("_destructuring_pattern"),
				),
			),
			Str("="),
			Field("right",
				Sym("expression"),
			),
		))

	g.Define("array",
		Seq(
			Str("["),
			Choice(
				Seq(
					Choice(
						Choice(
							Sym("expression"),
							Sym("spread_element"),
						),
						Blank(),
					),
					Repeat(
						Seq(
							Str(","),
							Choice(
								Choice(
									Sym("expression"),
									Sym("spread_element"),
								),
								Blank(),
							),
						),
					),
				),
				Blank(),
			),
			Str("]"),
		))

	g.Define("array_pattern",
		Seq(
			Str("["),
			Choice(
				Seq(
					Choice(
						Choice(
							Sym("pattern"),
							Sym("assignment_pattern"),
						),
						Blank(),
					),
					Repeat(
						Seq(
							Str(","),
							Choice(
								Choice(
									Sym("pattern"),
									Sym("assignment_pattern"),
								),
								Blank(),
							),
						),
					),
				),
				Blank(),
			),
			Str("]"),
		))

	g.Define("_jsx_element",
		Choice(
			Sym("jsx_element"),
			Sym("jsx_self_closing_element"),
		))

	g.Define("jsx_element",
		Seq(
			Field("open_tag",
				Sym("jsx_opening_element"),
			),
			Repeat(
				Sym("_jsx_child"),
			),
			Field("close_tag",
				Sym("jsx_closing_element"),
			),
		))

	g.Define("html_character_reference",
		Pat(`&(#([xX][0-9a-fA-F]{1,6}|[0-9]{1,5})|[A-Za-z]{1,30});`))

	g.Define("jsx_expression",
		Seq(
			Str("{"),
			Choice(
				Choice(
					Sym("expression"),
					Sym("sequence_expression"),
					Sym("spread_element"),
				),
				Blank(),
			),
			Str("}"),
		))

	g.Define("_jsx_child",
		Choice(
			Sym("jsx_text"),
			Sym("html_character_reference"),
			Sym("_jsx_element"),
			Sym("jsx_expression"),
		))

	g.Define("jsx_opening_element",
		PrecDynamic(-1,
			Seq(
				Sym("_jsx_start_opening_element"),
				Str(">"),
			),
		))

	g.Define("jsx_identifier",
		Pat(`[a-zA-Z_$][a-zA-Z\d_$]*-[a-zA-Z\d_$\-]*`))

	g.Define("_jsx_identifier",
		Choice(
			Alias(
				Sym("jsx_identifier"),
				"identifier", true,
			),
			Sym("identifier"),
		))

	g.Define("nested_identifier",
		Prec(35,
			Seq(
				Field("object",
					Choice(
						Sym("identifier"),
						Alias(
							Sym("nested_identifier"),
							"member_expression", true,
						),
					),
				),
				Str("."),
				Field("property",
					Alias(
						Sym("identifier"),
						"property_identifier", true,
					),
				),
			),
		))

	g.Define("jsx_namespace_name",
		Seq(
			Sym("_jsx_identifier"),
			Str(":"),
			Sym("_jsx_identifier"),
		))

	g.Define("_jsx_element_name",
		Choice(
			Sym("_jsx_identifier"),
			Alias(
				Sym("nested_identifier"),
				"member_expression", true,
			),
			Sym("jsx_namespace_name"),
		))

	g.Define("jsx_closing_element",
		Seq(
			Str("</"),
			Choice(
				Field("name",
					Sym("_jsx_element_name"),
				),
				Blank(),
			),
			Str(">"),
		))

	g.Define("jsx_self_closing_element",
		PrecDynamic(-1,
			Seq(
				Sym("_jsx_start_opening_element"),
				Str("/>"),
			),
		))

	g.Define("_jsx_attribute",
		Choice(
			Sym("jsx_attribute"),
			Sym("jsx_expression"),
		))

	g.Define("_jsx_attribute_name",
		Choice(
			Alias(
				Sym("_jsx_identifier"),
				"property_identifier", true,
			),
			Sym("jsx_namespace_name"),
		))

	g.Define("jsx_attribute",
		Seq(
			Sym("_jsx_attribute_name"),
			Choice(
				Seq(
					Str("="),
					Sym("_jsx_attribute_value"),
				),
				Blank(),
			),
		))

	g.Define("_jsx_string",
		Choice(
			Seq(
				Str("\""),
				Repeat(
					Choice(
						Alias(
							Sym("unescaped_double_jsx_string_fragment"),
							"string_fragment", true,
						),
						Sym("html_character_reference"),
					),
				),
				Str("\""),
			),
			Seq(
				Str("'"),
				Repeat(
					Choice(
						Alias(
							Sym("unescaped_single_jsx_string_fragment"),
							"string_fragment", true,
						),
						Sym("html_character_reference"),
					),
				),
				Str("'"),
			),
		))

	g.Define("unescaped_double_jsx_string_fragment",
		ImmToken(
			Prec(1,
				Pat(`([^"&]|&[^#A-Za-z])+`),
			),
		))

	g.Define("unescaped_single_jsx_string_fragment",
		ImmToken(
			Prec(1,
				Pat(`([^'&]|&[^#A-Za-z])+`),
			),
		))

	g.Define("_jsx_attribute_value",
		Choice(
			Alias(
				Sym("_jsx_string"),
				"string", true,
			),
			Sym("jsx_expression"),
			Sym("_jsx_element"),
		))

	g.Define("class",
		Prec(12,
			Seq(
				Repeat(
					Field("decorator",
						Sym("decorator"),
					),
				),
				Str("class"),
				Field("name",
					Choice(
						Sym("_type_identifier"),
						Blank(),
					),
				),
				Field("type_parameters",
					Choice(
						Sym("type_parameters"),
						Blank(),
					),
				),
				Choice(
					Sym("class_heritage"),
					Blank(),
				),
				Field("body",
					Sym("class_body"),
				),
			),
		))

	g.Define("class_declaration",
		PrecLeft(13,
			Seq(
				Repeat(
					Field("decorator",
						Sym("decorator"),
					),
				),
				Str("class"),
				Field("name",
					Sym("_type_identifier"),
				),
				Field("type_parameters",
					Choice(
						Sym("type_parameters"),
						Blank(),
					),
				),
				Choice(
					Sym("class_heritage"),
					Blank(),
				),
				Field("body",
					Sym("class_body"),
				),
				Choice(
					Sym("_automatic_semicolon"),
					Blank(),
				),
			),
		))

	g.Define("class_heritage",
		Choice(
			Seq(
				Sym("extends_clause"),
				Choice(
					Sym("implements_clause"),
					Blank(),
				),
			),
			Sym("implements_clause"),
		))

	g.Define("function_expression",
		Prec(12,
			Seq(
				Choice(
					Str("async"),
					Blank(),
				),
				Str("function"),
				Field("name",
					Choice(
						Sym("identifier"),
						Blank(),
					),
				),
				Sym("_call_signature"),
				Field("body",
					Sym("statement_block"),
				),
			),
		))

	g.Define("function_declaration",
		PrecRight(13,
			Seq(
				Choice(
					Str("async"),
					Blank(),
				),
				Str("function"),
				Field("name",
					Sym("identifier"),
				),
				Sym("_call_signature"),
				Field("body",
					Sym("statement_block"),
				),
				Choice(
					Sym("_automatic_semicolon"),
					Blank(),
				),
			),
		))

	g.Define("generator_function",
		Prec(12,
			Seq(
				Choice(
					Str("async"),
					Blank(),
				),
				Str("function"),
				Str("*"),
				Field("name",
					Choice(
						Sym("identifier"),
						Blank(),
					),
				),
				Sym("_call_signature"),
				Field("body",
					Sym("statement_block"),
				),
			),
		))

	g.Define("generator_function_declaration",
		PrecRight(13,
			Seq(
				Choice(
					Str("async"),
					Blank(),
				),
				Str("function"),
				Str("*"),
				Field("name",
					Sym("identifier"),
				),
				Sym("_call_signature"),
				Field("body",
					Sym("statement_block"),
				),
				Choice(
					Sym("_automatic_semicolon"),
					Blank(),
				),
			),
		))

	g.Define("arrow_function",
		Seq(
			Choice(
				Str("async"),
				Blank(),
			),
			Choice(
				Field("parameter",
					Choice(
						Alias(
							Sym("_reserved_identifier"),
							"identifier", true,
						),
						Sym("identifier"),
					),
				),
				Sym("_call_signature"),
			),
			Str("=>"),
			Field("body",
				Choice(
					Sym("expression"),
					Sym("statement_block"),
				),
			),
		))

	g.Define("_call_signature",
		Seq(
			Field("type_parameters",
				Choice(
					Sym("type_parameters"),
					Blank(),
				),
			),
			Field("parameters",
				Sym("formal_parameters"),
			),
			Field("return_type",
				Choice(
					Choice(
						Sym("type_annotation"),
						Sym("asserts_annotation"),
						Sym("type_predicate_annotation"),
					),
					Blank(),
				),
			),
		))

	g.Define("_formal_parameter",
		Choice(
			Sym("required_parameter"),
			Sym("optional_parameter"),
		))

	g.Define("optional_chain",
		Str("?."))

	g.Define("call_expression",
		Choice(
			Prec(33,
				Seq(
					Field("function",
						Choice(
							Sym("expression"),
							Sym("import"),
						),
					),
					Field("type_arguments",
						Choice(
							Sym("type_arguments"),
							Blank(),
						),
					),
					Field("arguments",
						Sym("arguments"),
					),
				),
			),
			Prec(34,
				Seq(
					Field("function",
						Choice(
							Sym("primary_expression"),
							Sym("new_expression"),
						),
					),
					Field("arguments",
						Sym("template_string"),
					),
				),
			),
			Prec(35,
				Seq(
					Field("function",
						Sym("primary_expression"),
					),
					Str("?."),
					Field("type_arguments",
						Choice(
							Sym("type_arguments"),
							Blank(),
						),
					),
					Field("arguments",
						Sym("arguments"),
					),
				),
			),
		))

	g.Define("new_expression",
		PrecRight(15,
			Seq(
				Str("new"),
				Field("constructor",
					Sym("primary_expression"),
				),
				Field("type_arguments",
					Choice(
						Sym("type_arguments"),
						Blank(),
					),
				),
				Field("arguments",
					Choice(
						Sym("arguments"),
						Blank(),
					),
				),
			),
		))

	g.Define("await_expression",
		Prec(32,
			Seq(
				Str("await"),
				Sym("expression"),
			),
		))

	g.Define("member_expression",
		Prec(35,
			Seq(
				Field("object",
					Choice(
						Sym("expression"),
						Sym("primary_expression"),
						Sym("import"),
					),
				),
				Choice(
					Str("."),
					Field("optional_chain",
						Sym("optional_chain"),
					),
				),
				Field("property",
					Choice(
						Sym("private_property_identifier"),
						Alias(
							Sym("identifier"),
							"property_identifier", true,
						),
					),
				),
			),
		))

	g.Define("subscript_expression",
		PrecRight(35,
			Seq(
				Field("object",
					Choice(
						Sym("expression"),
						Sym("primary_expression"),
					),
				),
				Choice(
					Field("optional_chain",
						Sym("optional_chain"),
					),
					Blank(),
				),
				Str("["),
				Field("index",
					Sym("_expressions"),
				),
				Str("]"),
			),
		))

	g.Define("_lhs_expression",
		Choice(
			Choice(
				Sym("member_expression"),
				Sym("subscript_expression"),
				Sym("_identifier"),
				Alias(
					Sym("_reserved_identifier"),
					"identifier", true,
				),
				Sym("_destructuring_pattern"),
			),
			Sym("non_null_expression"),
		))

	g.Define("assignment_expression",
		PrecRight(18,
			Seq(
				Choice(
					Str("using"),
					Blank(),
				),
				Field("left",
					Choice(
						Sym("parenthesized_expression"),
						Sym("_lhs_expression"),
					),
				),
				Str("="),
				Field("right",
					Sym("expression"),
				),
			),
		))

	g.Define("_augmented_assignment_lhs",
		Choice(
			Choice(
				Sym("member_expression"),
				Sym("subscript_expression"),
				Alias(
					Sym("_reserved_identifier"),
					"identifier", true,
				),
				Sym("identifier"),
				Sym("parenthesized_expression"),
			),
			Sym("non_null_expression"),
		))

	g.Define("augmented_assignment_expression",
		PrecRight(18,
			Seq(
				Field("left",
					Sym("_augmented_assignment_lhs"),
				),
				Field("operator",
					Choice(
						Str("+="),
						Str("-="),
						Str("*="),
						Str("/="),
						Str("%="),
						Str("^="),
						Str("&="),
						Str("|="),
						Str(">>="),
						Str(">>>="),
						Str("<<="),
						Str("**="),
						Str("&&="),
						Str("||="),
						Str("??="),
					),
				),
				Field("right",
					Sym("expression"),
				),
			),
		))

	g.Define("_initializer",
		Seq(
			Str("="),
			Field("value",
				Sym("expression"),
			),
		))

	g.Define("_destructuring_pattern",
		Choice(
			Sym("object_pattern"),
			Sym("array_pattern"),
		))

	g.Define("spread_element",
		Seq(
			Str("..."),
			Sym("expression"),
		))

	g.Define("ternary_expression",
		PrecRight(19,
			Seq(
				Field("condition",
					Sym("expression"),
				),
				Alias(
					Sym("_ternary_qmark"),
					"?", false,
				),
				Field("consequence",
					Sym("expression"),
				),
				Str(":"),
				Field("alternative",
					Sym("expression"),
				),
			),
		))

	g.Define("binary_expression",
		Choice(
			PrecLeft(21,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("&&"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(20,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("||"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(28,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str(">>"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(28,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str(">>>"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(28,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("<<"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(24,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("&"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(23,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("^"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(22,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("|"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(29,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("+"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(29,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("-"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(30,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("*"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(30,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("/"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(30,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("%"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecRight(31,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("**"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(26,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("<"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(26,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("<="),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(25,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("=="),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(25,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("==="),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(25,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("!="),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(25,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("!=="),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(26,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str(">="),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(26,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str(">"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(19,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("??"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(26,
				Seq(
					Field("left",
						Sym("expression"),
					),
					Field("operator",
						Str("instanceof"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
			PrecLeft(26,
				Seq(
					Field("left",
						Choice(
							Sym("expression"),
							Sym("private_property_identifier"),
						),
					),
					Field("operator",
						Str("in"),
					),
					Field("right",
						Sym("expression"),
					),
				),
			),
		))

	g.Define("unary_expression",
		PrecLeft(32,
			Seq(
				Field("operator",
					Choice(
						Str("!"),
						Str("~"),
						Str("-"),
						Str("+"),
						Str("typeof"),
						Str("void"),
						Str("delete"),
					),
				),
				Field("argument",
					Sym("expression"),
				),
			),
		))

	g.Define("update_expression",
		PrecLeft(0,
			Choice(
				Seq(
					Field("argument",
						Sym("expression"),
					),
					Field("operator",
						Choice(
							Str("++"),
							Str("--"),
						),
					),
				),
				Seq(
					Field("operator",
						Choice(
							Str("++"),
							Str("--"),
						),
					),
					Field("argument",
						Sym("expression"),
					),
				),
			),
		))

	g.Define("sequence_expression",
		PrecRight(0,
			Seq(
				Sym("expression"),
				Repeat(
					Seq(
						Str(","),
						Sym("expression"),
					),
				),
			),
		))

	g.Define("string",
		Choice(
			Seq(
				Str("\""),
				Repeat(
					Choice(
						Alias(
							Sym("unescaped_double_string_fragment"),
							"string_fragment", true,
						),
						Sym("escape_sequence"),
					),
				),
				Str("\""),
			),
			Seq(
				Str("'"),
				Repeat(
					Choice(
						Alias(
							Sym("unescaped_single_string_fragment"),
							"string_fragment", true,
						),
						Sym("escape_sequence"),
					),
				),
				Str("'"),
			),
		))

	g.Define("unescaped_double_string_fragment",
		ImmToken(
			Prec(1,
				Pat(`[^"\\\r\n]+`),
			),
		))

	g.Define("unescaped_single_string_fragment",
		ImmToken(
			Prec(1,
				Pat(`[^'\\\r\n]+`),
			),
		))

	g.Define("escape_sequence",
		ImmToken(
			Seq(
				Str("\\"),
				Choice(
					Pat(`[^xu0-7]`),
					Pat(`[0-7]{1,3}`),
					Pat(`x[0-9a-fA-F]{2}`),
					Pat(`u[0-9a-fA-F]{4}`),
					Pat(`u\{[0-9a-fA-F]+\}`),
					Pat(`[\r?][\n\u2028\u2029]`),
				),
			),
		))

	g.Define("comment",
		Token(
			Choice(
				Seq(
					Str("//"),
					Pat(`[^\r\n\u2028\u2029]*`),
				),
				Seq(
					Str("/*"),
					Pat(`[^*]*\*+([^/*][^*]*\*+)*`),
					Str("/"),
				),
			),
		))

	g.Define("template_string",
		Seq(
			Str("`"),
			Repeat(
				Choice(
					Alias(
						Sym("_template_chars"),
						"string_fragment", true,
					),
					Sym("escape_sequence"),
					Sym("template_substitution"),
				),
			),
			Str("`"),
		))

	g.Define("template_substitution",
		Seq(
			Str("${"),
			Sym("_expressions"),
			Str("}"),
		))

	g.Define("regex",
		Seq(
			Str("/"),
			Field("pattern",
				Sym("regex_pattern"),
			),
			ImmToken(
				Prec(1,
					Str("/"),
				),
			),
			Choice(
				Field("flags",
					Sym("regex_flags"),
				),
				Blank(),
			),
		))

	g.Define("regex_pattern",
		ImmToken(
			Prec(-1,
				Repeat1(
					Choice(
						Seq(
							Str("["),
							Repeat(
								Choice(
									Seq(
										Str("\\"),
										Pat(`.`),
									),
									Pat(`[^\]\n\\]`),
								),
							),
							Str("]"),
						),
						Seq(
							Str("\\"),
							Pat(`.`),
						),
						Pat(`[^/\\\[\n]`),
					),
				),
			),
		))

	g.Define("regex_flags",
		ImmToken(
			Pat(`[a-z]+`),
		))

	g.Define("number",
		Token(
			Choice(
				Seq(
					Choice(
						Str("0x"),
						Str("0X"),
					),
					Pat(`[\da-fA-F](_?[\da-fA-F])*`),
				),
				Choice(
					Seq(
						Choice(
							Str("0"),
							Seq(
								Choice(
									Str("0"),
									Blank(),
								),
								Pat(`[1-9]`),
								Choice(
									Seq(
										Choice(
											Str("_"),
											Blank(),
										),
										Pat(`\d(_?\d)*`),
									),
									Blank(),
								),
							),
						),
						Str("."),
						Choice(
							Pat(`\d(_?\d)*`),
							Blank(),
						),
						Choice(
							Seq(
								Choice(
									Str("e"),
									Str("E"),
								),
								Seq(
									Choice(
										Choice(
											Str("-"),
											Str("+"),
										),
										Blank(),
									),
									Pat(`\d(_?\d)*`),
								),
							),
							Blank(),
						),
					),
					Seq(
						Str("."),
						Pat(`\d(_?\d)*`),
						Choice(
							Seq(
								Choice(
									Str("e"),
									Str("E"),
								),
								Seq(
									Choice(
										Choice(
											Str("-"),
											Str("+"),
										),
										Blank(),
									),
									Pat(`\d(_?\d)*`),
								),
							),
							Blank(),
						),
					),
					Seq(
						Choice(
							Str("0"),
							Seq(
								Choice(
									Str("0"),
									Blank(),
								),
								Pat(`[1-9]`),
								Choice(
									Seq(
										Choice(
											Str("_"),
											Blank(),
										),
										Pat(`\d(_?\d)*`),
									),
									Blank(),
								),
							),
						),
						Seq(
							Choice(
								Str("e"),
								Str("E"),
							),
							Seq(
								Choice(
									Choice(
										Str("-"),
										Str("+"),
									),
									Blank(),
								),
								Pat(`\d(_?\d)*`),
							),
						),
					),
					Pat(`\d(_?\d)*`),
				),
				Seq(
					Choice(
						Str("0b"),
						Str("0B"),
					),
					Pat(`[0-1](_?[0-1])*`),
				),
				Seq(
					Choice(
						Str("0o"),
						Str("0O"),
					),
					Pat(`[0-7](_?[0-7])*`),
				),
				Seq(
					Choice(
						Seq(
							Choice(
								Str("0x"),
								Str("0X"),
							),
							Pat(`[\da-fA-F](_?[\da-fA-F])*`),
						),
						Seq(
							Choice(
								Str("0b"),
								Str("0B"),
							),
							Pat(`[0-1](_?[0-1])*`),
						),
						Seq(
							Choice(
								Str("0o"),
								Str("0O"),
							),
							Pat(`[0-7](_?[0-7])*`),
						),
						Pat(`\d(_?\d)*`),
					),
					Str("n"),
				),
			),
		))

	g.Define("_identifier",
		Choice(
			Sym("undefined"),
			Sym("identifier"),
		))

	g.Define("identifier",
		Token(
			Seq(
				Pat("[^\\x00-\\x1F\\s\\p{Zs}0-9:;`\"'@#.,|^&<=>+\\-*/\\\\%?!~()\\[\\]{}\\uFEFF\\u2060\\u200B\\u2028\\u2029]|\\\\u[0-9a-fA-F]{4}|\\\\u\\{[0-9a-fA-F]+\\}"),
				Repeat(
					Pat("[^\\x00-\\x1F\\s\\p{Zs}:;`\"'@#.,|^&<=>+\\-*/\\\\%?!~()\\[\\]{}\\uFEFF\\u2060\\u200B\\u2028\\u2029]|\\\\u[0-9a-fA-F]{4}|\\\\u\\{[0-9a-fA-F]+\\}"),
				),
			),
		))

	g.Define("private_property_identifier",
		Token(
			Seq(
				Str("#"),
				Pat("[^\\x00-\\x1F\\s\\p{Zs}0-9:;`\"'@#.,|^&<=>+\\-*/\\\\%?!~()\\[\\]{}\\uFEFF\\u2060\\u200B\\u2028\\u2029]|\\\\u[0-9a-fA-F]{4}|\\\\u\\{[0-9a-fA-F]+\\}"),
				Repeat(
					Pat("[^\\x00-\\x1F\\s\\p{Zs}:;`\"'@#.,|^&<=>+\\-*/\\\\%?!~()\\[\\]{}\\uFEFF\\u2060\\u200B\\u2028\\u2029]|\\\\u[0-9a-fA-F]{4}|\\\\u\\{[0-9a-fA-F]+\\}"),
				),
			),
		))

	g.Define("meta_property",
		Choice(
			Seq(
				Str("new"),
				Str("."),
				Str("target"),
			),
			Seq(
				Str("import"),
				Str("."),
				Str("meta"),
			),
		))

	g.Define("this",
		Str("this"))

	g.Define("super",
		Str("super"))

	g.Define("true",
		Str("true"))

	g.Define("false",
		Str("false"))

	g.Define("null",
		Str("null"))

	g.Define("undefined",
		Str("undefined"))

	g.Define("arguments",
		Seq(
			Str("("),
			Choice(
				Seq(
					Choice(
						Choice(
							Sym("expression"),
							Sym("spread_element"),
						),
						Blank(),
					),
					Repeat(
						Seq(
							Str(","),
							Choice(
								Choice(
									Sym("expression"),
									Sym("spread_element"),
								),
								Blank(),
							),
						),
					),
				),
				Blank(),
			),
			Str(")"),
		))

	g.Define("decorator",
		Seq(
			Str("@"),
			Choice(
				Sym("identifier"),
				Alias(
					Sym("decorator_member_expression"),
					"member_expression", true,
				),
				Alias(
					Sym("decorator_call_expression"),
					"call_expression", true,
				),
				Alias(
					Sym("decorator_parenthesized_expression"),
					"parenthesized_expression", true,
				),
			),
		))

	g.Define("decorator_member_expression",
		Prec(35,
			Seq(
				Field("object",
					Choice(
						Sym("identifier"),
						Alias(
							Sym("decorator_member_expression"),
							"member_expression", true,
						),
					),
				),
				Str("."),
				Field("property",
					Alias(
						Sym("identifier"),
						"property_identifier", true,
					),
				),
			),
		))

	g.Define("decorator_call_expression",
		Prec(33,
			Seq(
				Field("function",
					Choice(
						Sym("identifier"),
						Alias(
							Sym("decorator_member_expression"),
							"member_expression", true,
						),
					),
				),
				Choice(
					Field("type_arguments",
						Sym("type_arguments"),
					),
					Blank(),
				),
				Field("arguments",
					Sym("arguments"),
				),
			),
		))

	g.Define("class_body",
		Seq(
			Str("{"),
			Repeat(
				Choice(
					Seq(
						Repeat(
							Field("decorator",
								Sym("decorator"),
							),
						),
						Sym("method_definition"),
						Choice(
							Sym("_semicolon"),
							Blank(),
						),
					),
					Seq(
						Sym("method_signature"),
						Choice(
							Sym("_function_signature_automatic_semicolon"),
							Str(","),
						),
					),
					Sym("class_static_block"),
					Seq(
						Choice(
							Sym("abstract_method_signature"),
							Sym("index_signature"),
							Sym("method_signature"),
							Sym("public_field_definition"),
						),
						Choice(
							Sym("_semicolon"),
							Str(","),
						),
					),
					Str(";"),
				),
			),
			Str("}"),
		))

	g.Define("field_definition",
		Seq(
			Repeat(
				Field("decorator",
					Sym("decorator"),
				),
			),
			Choice(
				Str("static"),
				Blank(),
			),
			Field("property",
				Sym("_property_name"),
			),
			Choice(
				Sym("_initializer"),
				Blank(),
			),
		))

	g.Define("formal_parameters",
		Seq(
			Str("("),
			Choice(
				Seq(
					Seq(
						Sym("_formal_parameter"),
						Repeat(
							Seq(
								Str(","),
								Sym("_formal_parameter"),
							),
						),
					),
					Choice(
						Str(","),
						Blank(),
					),
				),
				Blank(),
			),
			Str(")"),
		))

	g.Define("class_static_block",
		Seq(
			Str("static"),
			Choice(
				Sym("_automatic_semicolon"),
				Blank(),
			),
			Field("body",
				Sym("statement_block"),
			),
		))

	g.Define("pattern",
		PrecDynamic(-1,
			Choice(
				Sym("_lhs_expression"),
				Sym("rest_pattern"),
			),
		))

	g.Define("rest_pattern",
		PrecRight(0,
			Seq(
				Str("..."),
				Sym("_lhs_expression"),
			),
		))

	g.Define("method_definition",
		PrecLeft(0,
			Seq(
				Choice(
					Sym("accessibility_modifier"),
					Blank(),
				),
				Choice(
					Str("static"),
					Blank(),
				),
				Choice(
					Sym("override_modifier"),
					Blank(),
				),
				Choice(
					Str("readonly"),
					Blank(),
				),
				Choice(
					Str("async"),
					Blank(),
				),
				Choice(
					Choice(
						Str("get"),
						Str("set"),
						Str("*"),
					),
					Blank(),
				),
				Field("name",
					Sym("_property_name"),
				),
				Choice(
					Str("?"),
					Blank(),
				),
				Sym("_call_signature"),
				Field("body",
					Sym("statement_block"),
				),
			),
		))

	g.Define("pair",
		Seq(
			Field("key",
				Sym("_property_name"),
			),
			Str(":"),
			Field("value",
				Sym("expression"),
			),
		))

	g.Define("pair_pattern",
		Seq(
			Field("key",
				Sym("_property_name"),
			),
			Str(":"),
			Field("value",
				Choice(
					Sym("pattern"),
					Sym("assignment_pattern"),
				),
			),
		))

	g.Define("_property_name",
		Choice(
			Alias(
				Choice(
					Sym("identifier"),
					Sym("_reserved_identifier"),
				),
				"property_identifier", true,
			),
			Sym("private_property_identifier"),
			Sym("string"),
			Sym("number"),
			Sym("computed_property_name"),
		))

	g.Define("computed_property_name",
		Seq(
			Str("["),
			Sym("expression"),
			Str("]"),
		))

	g.Define("_reserved_identifier",
		Choice(
			Str("declare"),
			Str("namespace"),
			Str("type"),
			Str("public"),
			Str("private"),
			Str("protected"),
			Str("override"),
			Str("readonly"),
			Str("module"),
			Str("any"),
			Str("number"),
			Str("boolean"),
			Str("string"),
			Str("symbol"),
			Str("export"),
			Str("object"),
			Str("new"),
			Str("readonly"),
			Choice(
				Str("get"),
				Str("set"),
				Str("async"),
				Str("static"),
				Str("export"),
				Str("let"),
			),
		))

	g.Define("_semicolon",
		Choice(
			Sym("_automatic_semicolon"),
			Str(";"),
		))

	g.Define("public_field_definition",
		Seq(
			Repeat(
				Field("decorator",
					Sym("decorator"),
				),
			),
			Choice(
				Choice(
					Seq(
						Str("declare"),
						Choice(
							Sym("accessibility_modifier"),
							Blank(),
						),
					),
					Seq(
						Sym("accessibility_modifier"),
						Choice(
							Str("declare"),
							Blank(),
						),
					),
				),
				Blank(),
			),
			Choice(
				Seq(
					Choice(
						Str("static"),
						Blank(),
					),
					Choice(
						Sym("override_modifier"),
						Blank(),
					),
					Choice(
						Str("readonly"),
						Blank(),
					),
				),
				Seq(
					Choice(
						Str("abstract"),
						Blank(),
					),
					Choice(
						Str("readonly"),
						Blank(),
					),
				),
				Seq(
					Choice(
						Str("readonly"),
						Blank(),
					),
					Choice(
						Str("abstract"),
						Blank(),
					),
				),
				Choice(
					Str("accessor"),
					Blank(),
				),
			),
			Field("name",
				Sym("_property_name"),
			),
			Choice(
				Choice(
					Str("?"),
					Str("!"),
				),
				Blank(),
			),
			Field("type",
				Choice(
					Sym("type_annotation"),
					Blank(),
				),
			),
			Choice(
				Sym("_initializer"),
				Blank(),
			),
		))

	g.Define("_jsx_start_opening_element",
		Seq(
			Str("<"),
			Choice(
				Seq(
					Choice(
						Field("name",
							Choice(
								Sym("_jsx_identifier"),
								Sym("jsx_namespace_name"),
							),
						),
						Seq(
							Field("name",
								Choice(
									Sym("identifier"),
									Alias(
										Sym("nested_identifier"),
										"member_expression", true,
									),
								),
							),
							Field("type_arguments",
								Choice(
									Sym("type_arguments"),
									Blank(),
								),
							),
						),
					),
					Repeat(
						Field("attribute",
							Sym("_jsx_attribute"),
						),
					),
				),
				Blank(),
			),
		))

	g.Define("_import_identifier",
		Choice(
			Sym("identifier"),
			Alias(
				Str("type"),
				"identifier", true,
			),
		))

	g.Define("non_null_expression",
		PrecLeft(8,
			Seq(
				Sym("expression"),
				Str("!"),
			),
		))

	g.Define("method_signature",
		Seq(
			Choice(
				Sym("accessibility_modifier"),
				Blank(),
			),
			Choice(
				Str("static"),
				Blank(),
			),
			Choice(
				Sym("override_modifier"),
				Blank(),
			),
			Choice(
				Str("readonly"),
				Blank(),
			),
			Choice(
				Str("async"),
				Blank(),
			),
			Choice(
				Choice(
					Str("get"),
					Str("set"),
					Str("*"),
				),
				Blank(),
			),
			Field("name",
				Sym("_property_name"),
			),
			Choice(
				Str("?"),
				Blank(),
			),
			Sym("_call_signature"),
		))

	g.Define("abstract_method_signature",
		Seq(
			Choice(
				Sym("accessibility_modifier"),
				Blank(),
			),
			Str("abstract"),
			Choice(
				Sym("override_modifier"),
				Blank(),
			),
			Choice(
				Choice(
					Str("get"),
					Str("set"),
					Str("*"),
				),
				Blank(),
			),
			Field("name",
				Sym("_property_name"),
			),
			Choice(
				Str("?"),
				Blank(),
			),
			Sym("_call_signature"),
		))

	g.Define("function_signature",
		Seq(
			Choice(
				Str("async"),
				Blank(),
			),
			Str("function"),
			Field("name",
				Sym("identifier"),
			),
			Sym("_call_signature"),
			Choice(
				Sym("_semicolon"),
				Sym("_function_signature_automatic_semicolon"),
			),
		))

	g.Define("decorator_parenthesized_expression",
		Seq(
			Str("("),
			Choice(
				Sym("identifier"),
				Alias(
					Sym("decorator_member_expression"),
					"member_expression", true,
				),
				Alias(
					Sym("decorator_call_expression"),
					"call_expression", true,
				),
			),
			Str(")"),
		))

	g.Define("type_assertion",
		PrecLeft(8,
			Seq(
				Sym("type_arguments"),
				Sym("expression"),
			),
		))

	g.Define("as_expression",
		PrecLeft(7,
			Seq(
				Sym("expression"),
				Str("as"),
				Choice(
					Str("const"),
					Sym("type"),
				),
			),
		))

	g.Define("satisfies_expression",
		PrecLeft(7,
			Seq(
				Sym("expression"),
				Str("satisfies"),
				Sym("type"),
			),
		))

	g.Define("instantiation_expression",
		Prec(9,
			Seq(
				Sym("expression"),
				Field("type_arguments",
					Sym("type_arguments"),
				),
			),
		))

	g.Define("import_require_clause",
		Seq(
			Sym("identifier"),
			Str("="),
			Str("require"),
			Str("("),
			Field("source",
				Sym("string"),
			),
			Str(")"),
		))

	g.Define("extends_clause",
		Seq(
			Str("extends"),
			Seq(
				Sym("_extends_clause_single"),
				Repeat(
					Seq(
						Str(","),
						Sym("_extends_clause_single"),
					),
				),
			),
		))

	g.Define("_extends_clause_single",
		Prec(6,
			Seq(
				Field("value",
					Sym("expression"),
				),
				Field("type_arguments",
					Choice(
						Sym("type_arguments"),
						Blank(),
					),
				),
			),
		))

	g.Define("implements_clause",
		Seq(
			Str("implements"),
			Seq(
				Sym("type"),
				Repeat(
					Seq(
						Str(","),
						Sym("type"),
					),
				),
			),
		))

	g.Define("ambient_declaration",
		Seq(
			Str("declare"),
			Choice(
				Sym("declaration"),
				Seq(
					Str("global"),
					Sym("statement_block"),
				),
				Seq(
					Str("module"),
					Str("."),
					Alias(
						Sym("identifier"),
						"property_identifier", true,
					),
					Str(":"),
					Sym("type"),
					Sym("_semicolon"),
				),
			),
		))

	g.Define("abstract_class_declaration",
		Prec(13,
			Seq(
				Repeat(
					Field("decorator",
						Sym("decorator"),
					),
				),
				Str("abstract"),
				Str("class"),
				Field("name",
					Sym("_type_identifier"),
				),
				Field("type_parameters",
					Choice(
						Sym("type_parameters"),
						Blank(),
					),
				),
				Choice(
					Sym("class_heritage"),
					Blank(),
				),
				Field("body",
					Sym("class_body"),
				),
			),
		))

	g.Define("module",
		Seq(
			Str("module"),
			Sym("_module"),
		))

	g.Define("internal_module",
		Seq(
			Str("namespace"),
			Sym("_module"),
		))

	g.Define("_module",
		PrecRight(0,
			Seq(
				Field("name",
					Choice(
						Sym("string"),
						Sym("identifier"),
						Sym("nested_identifier"),
					),
				),
				Field("body",
					Choice(
						Sym("statement_block"),
						Blank(),
					),
				),
			),
		))

	g.Define("import_alias",
		Seq(
			Str("import"),
			Sym("identifier"),
			Str("="),
			Choice(
				Sym("identifier"),
				Sym("nested_identifier"),
			),
			Sym("_semicolon"),
		))

	g.Define("nested_type_identifier",
		Prec(35,
			Seq(
				Field("module",
					Choice(
						Sym("identifier"),
						Sym("nested_identifier"),
					),
				),
				Str("."),
				Field("name",
					Sym("_type_identifier"),
				),
			),
		))

	g.Define("interface_declaration",
		Seq(
			Str("interface"),
			Field("name",
				Sym("_type_identifier"),
			),
			Field("type_parameters",
				Choice(
					Sym("type_parameters"),
					Blank(),
				),
			),
			Choice(
				Sym("extends_type_clause"),
				Blank(),
			),
			Field("body",
				Alias(
					Sym("object_type"),
					"interface_body", true,
				),
			),
		))

	g.Define("extends_type_clause",
		Seq(
			Str("extends"),
			Seq(
				Field("type",
					Choice(
						Sym("_type_identifier"),
						Sym("nested_type_identifier"),
						Sym("generic_type"),
					),
				),
				Repeat(
					Seq(
						Str(","),
						Field("type",
							Choice(
								Sym("_type_identifier"),
								Sym("nested_type_identifier"),
								Sym("generic_type"),
							),
						),
					),
				),
			),
		))

	g.Define("enum_declaration",
		Seq(
			Choice(
				Str("const"),
				Blank(),
			),
			Str("enum"),
			Field("name",
				Sym("identifier"),
			),
			Field("body",
				Sym("enum_body"),
			),
		))

	g.Define("enum_body",
		Seq(
			Str("{"),
			Choice(
				Seq(
					Seq(
						Choice(
							Field("name",
								Sym("_property_name"),
							),
							Sym("enum_assignment"),
						),
						Repeat(
							Seq(
								Str(","),
								Choice(
									Field("name",
										Sym("_property_name"),
									),
									Sym("enum_assignment"),
								),
							),
						),
					),
					Choice(
						Str(","),
						Blank(),
					),
				),
				Blank(),
			),
			Str("}"),
		))

	g.Define("enum_assignment",
		Seq(
			Field("name",
				Sym("_property_name"),
			),
			Sym("_initializer"),
		))

	g.Define("type_alias_declaration",
		Seq(
			Str("type"),
			Field("name",
				Sym("_type_identifier"),
			),
			Field("type_parameters",
				Choice(
					Sym("type_parameters"),
					Blank(),
				),
			),
			Str("="),
			Field("value",
				Sym("type"),
			),
			Sym("_semicolon"),
		))

	g.Define("accessibility_modifier",
		Choice(
			Str("public"),
			Str("private"),
			Str("protected"),
		))

	g.Define("override_modifier",
		Str("override"))

	g.Define("required_parameter",
		Seq(
			Sym("_parameter_name"),
			Field("type",
				Choice(
					Sym("type_annotation"),
					Blank(),
				),
			),
			Choice(
				Sym("_initializer"),
				Blank(),
			),
		))

	g.Define("optional_parameter",
		Seq(
			Sym("_parameter_name"),
			Str("?"),
			Field("type",
				Choice(
					Sym("type_annotation"),
					Blank(),
				),
			),
			Choice(
				Sym("_initializer"),
				Blank(),
			),
		))

	g.Define("_parameter_name",
		Seq(
			Repeat(
				Field("decorator",
					Sym("decorator"),
				),
			),
			Choice(
				Sym("accessibility_modifier"),
				Blank(),
			),
			Choice(
				Sym("override_modifier"),
				Blank(),
			),
			Choice(
				Str("readonly"),
				Blank(),
			),
			Field("pattern",
				Choice(
					Sym("pattern"),
					Sym("this"),
				),
			),
		))

	g.Define("omitting_type_annotation",
		Seq(
			Str("-?:"),
			Sym("type"),
		))

	g.Define("adding_type_annotation",
		Seq(
			Str("+?:"),
			Sym("type"),
		))

	g.Define("opting_type_annotation",
		Seq(
			Str("?:"),
			Sym("type"),
		))

	g.Define("type_annotation",
		Seq(
			Str(":"),
			Sym("type"),
		))

	g.Define("_type_query_member_expression_in_type_annotation",
		Seq(
			Field("object",
				Choice(
					Sym("import"),
					Alias(
						Sym("_type_query_member_expression_in_type_annotation"),
						"member_expression", true,
					),
					Alias(
						Sym("_type_query_call_expression_in_type_annotation"),
						"call_expression", true,
					),
				),
			),
			Str("."),
			Field("property",
				Choice(
					Sym("private_property_identifier"),
					Alias(
						Sym("identifier"),
						"property_identifier", true,
					),
				),
			),
		))

	g.Define("_type_query_call_expression_in_type_annotation",
		Seq(
			Field("function",
				Choice(
					Sym("import"),
					Alias(
						Sym("_type_query_member_expression_in_type_annotation"),
						"member_expression", true,
					),
				),
			),
			Field("arguments",
				Sym("arguments"),
			),
		))

	g.Define("asserts",
		Seq(
			Str("asserts"),
			Choice(
				Sym("type_predicate"),
				Sym("identifier"),
				Sym("this"),
			),
		))

	g.Define("asserts_annotation",
		Seq(
			Seq(
				Str(":"),
				Sym("asserts"),
			),
		))

	g.Define("type",
		Choice(
			Sym("primary_type"),
			Sym("function_type"),
			Sym("readonly_type"),
			Sym("constructor_type"),
			Sym("infer_type"),
			Prec(-1,
				Alias(
					Sym("_type_query_member_expression_in_type_annotation"),
					"member_expression", true,
				),
			),
			Prec(-1,
				Alias(
					Sym("_type_query_call_expression_in_type_annotation"),
					"call_expression", true,
				),
			),
		))

	g.Define("tuple_parameter",
		Seq(
			Field("name",
				Choice(
					Sym("identifier"),
					Sym("rest_pattern"),
				),
			),
			Field("type",
				Sym("type_annotation"),
			),
		))

	g.Define("optional_tuple_parameter",
		Seq(
			Field("name",
				Sym("identifier"),
			),
			Str("?"),
			Field("type",
				Sym("type_annotation"),
			),
		))

	g.Define("optional_type",
		Seq(
			Sym("type"),
			Str("?"),
		))

	g.Define("rest_type",
		Seq(
			Str("..."),
			Sym("type"),
		))

	g.Define("_tuple_type_member",
		Choice(
			Alias(
				Sym("tuple_parameter"),
				"required_parameter", true,
			),
			Alias(
				Sym("optional_tuple_parameter"),
				"optional_parameter", true,
			),
			Sym("optional_type"),
			Sym("rest_type"),
			Sym("type"),
		))

	g.Define("constructor_type",
		PrecLeft(0,
			Seq(
				Choice(
					Str("abstract"),
					Blank(),
				),
				Str("new"),
				Field("type_parameters",
					Choice(
						Sym("type_parameters"),
						Blank(),
					),
				),
				Field("parameters",
					Sym("formal_parameters"),
				),
				Str("=>"),
				Field("type",
					Sym("type"),
				),
			),
		))

	g.Define("primary_type",
		Choice(
			Sym("parenthesized_type"),
			Sym("predefined_type"),
			Sym("_type_identifier"),
			Sym("nested_type_identifier"),
			Sym("generic_type"),
			Sym("object_type"),
			Sym("array_type"),
			Sym("tuple_type"),
			Sym("flow_maybe_type"),
			Sym("type_query"),
			Sym("index_type_query"),
			Alias(
				Sym("this"),
				"this_type", true,
			),
			Sym("existential_type"),
			Sym("literal_type"),
			Sym("lookup_type"),
			Sym("conditional_type"),
			Sym("template_literal_type"),
			Sym("intersection_type"),
			Sym("union_type"),
			Str("const"),
		))

	g.Define("template_type",
		Seq(
			Str("${"),
			Choice(
				Sym("primary_type"),
				Sym("infer_type"),
			),
			Str("}"),
		))

	g.Define("template_literal_type",
		Seq(
			Str("`"),
			Repeat(
				Choice(
					Alias(
						Sym("_template_chars"),
						"string_fragment", true,
					),
					Sym("template_type"),
				),
			),
			Str("`"),
		))

	g.Define("infer_type",
		PrecRight(0,
			Seq(
				Str("infer"),
				Sym("_type_identifier"),
				Choice(
					Seq(
						Str("extends"),
						Sym("type"),
					),
					Blank(),
				),
			),
		))

	g.Define("conditional_type",
		PrecRight(0,
			Seq(
				Field("left",
					Sym("type"),
				),
				Str("extends"),
				Field("right",
					Sym("type"),
				),
				Str("?"),
				Field("consequence",
					Sym("type"),
				),
				Str(":"),
				Field("alternative",
					Sym("type"),
				),
			),
		))

	g.Define("generic_type",
		Prec(33,
			Seq(
				Field("name",
					Choice(
						Sym("_type_identifier"),
						Sym("nested_type_identifier"),
					),
				),
				Field("type_arguments",
					Sym("type_arguments"),
				),
			),
		))

	g.Define("type_predicate",
		Seq(
			Field("name",
				Choice(
					Sym("identifier"),
					Sym("this"),
					Alias(
						Sym("predefined_type"),
						"identifier", true,
					),
				),
			),
			Str("is"),
			Field("type",
				Sym("type"),
			),
		))

	g.Define("type_predicate_annotation",
		Seq(
			Seq(
				Str(":"),
				Sym("type_predicate"),
			),
		))

	g.Define("_type_query_member_expression",
		Seq(
			Field("object",
				Choice(
					Sym("identifier"),
					Sym("this"),
					Alias(
						Sym("_type_query_subscript_expression"),
						"subscript_expression", true,
					),
					Alias(
						Sym("_type_query_member_expression"),
						"member_expression", true,
					),
					Alias(
						Sym("_type_query_call_expression"),
						"call_expression", true,
					),
				),
			),
			Choice(
				Str("."),
				Str("?."),
			),
			Field("property",
				Choice(
					Sym("private_property_identifier"),
					Alias(
						Sym("identifier"),
						"property_identifier", true,
					),
				),
			),
		))

	g.Define("_type_query_subscript_expression",
		Seq(
			Field("object",
				Choice(
					Sym("identifier"),
					Sym("this"),
					Alias(
						Sym("_type_query_subscript_expression"),
						"subscript_expression", true,
					),
					Alias(
						Sym("_type_query_member_expression"),
						"member_expression", true,
					),
					Alias(
						Sym("_type_query_call_expression"),
						"call_expression", true,
					),
				),
			),
			Choice(
				Str("?."),
				Blank(),
			),
			Str("["),
			Field("index",
				Choice(
					Sym("predefined_type"),
					Sym("string"),
					Sym("number"),
				),
			),
			Str("]"),
		))

	g.Define("_type_query_call_expression",
		Seq(
			Field("function",
				Choice(
					Sym("import"),
					Sym("identifier"),
					Alias(
						Sym("_type_query_member_expression"),
						"member_expression", true,
					),
					Alias(
						Sym("_type_query_subscript_expression"),
						"subscript_expression", true,
					),
				),
			),
			Field("arguments",
				Sym("arguments"),
			),
		))

	g.Define("_type_query_instantiation_expression",
		Seq(
			Field("function",
				Choice(
					Sym("import"),
					Sym("identifier"),
					Alias(
						Sym("_type_query_member_expression"),
						"member_expression", true,
					),
					Alias(
						Sym("_type_query_subscript_expression"),
						"subscript_expression", true,
					),
				),
			),
			Field("type_arguments",
				Sym("type_arguments"),
			),
		))

	g.Define("type_query",
		PrecRight(0,
			Seq(
				Str("typeof"),
				Choice(
					Alias(
						Sym("_type_query_subscript_expression"),
						"subscript_expression", true,
					),
					Alias(
						Sym("_type_query_member_expression"),
						"member_expression", true,
					),
					Alias(
						Sym("_type_query_call_expression"),
						"call_expression", true,
					),
					Alias(
						Sym("_type_query_instantiation_expression"),
						"instantiation_expression", true,
					),
					Sym("identifier"),
					Sym("this"),
				),
			),
		))

	g.Define("index_type_query",
		Seq(
			Str("keyof"),
			Sym("primary_type"),
		))

	g.Define("lookup_type",
		Seq(
			Sym("primary_type"),
			Str("["),
			Sym("type"),
			Str("]"),
		))

	g.Define("mapped_type_clause",
		Seq(
			Field("name",
				Sym("_type_identifier"),
			),
			Str("in"),
			Field("type",
				Sym("type"),
			),
			Choice(
				Seq(
					Str("as"),
					Field("alias",
						Sym("type"),
					),
				),
				Blank(),
			),
		))

	g.Define("literal_type",
		Choice(
			Alias(
				Sym("_number"),
				"unary_expression", true,
			),
			Sym("number"),
			Sym("string"),
			Sym("true"),
			Sym("false"),
			Sym("null"),
			Sym("undefined"),
		))

	g.Define("_number",
		PrecLeft(1,
			Seq(
				Field("operator",
					Choice(
						Str("-"),
						Str("+"),
					),
				),
				Field("argument",
					Sym("number"),
				),
			),
		))

	g.Define("existential_type",
		Str("*"))

	g.Define("flow_maybe_type",
		PrecRight(0,
			Seq(
				Str("?"),
				Sym("primary_type"),
			),
		))

	g.Define("parenthesized_type",
		Seq(
			Str("("),
			Sym("type"),
			Str(")"),
		))

	g.Define("predefined_type",
		Choice(
			Str("any"),
			Str("number"),
			Str("boolean"),
			Str("string"),
			Str("symbol"),
			Alias(
				Seq(
					Str("unique"),
					Str("symbol"),
				),
				"unique symbol", false,
			),
			Str("void"),
			Str("unknown"),
			Str("string"),
			Str("never"),
			Str("object"),
		))

	g.Define("type_arguments",
		Seq(
			Str("<"),
			Seq(
				Sym("type"),
				Repeat(
					Seq(
						Str(","),
						Sym("type"),
					),
				),
			),
			Choice(
				Str(","),
				Blank(),
			),
			Str(">"),
		))

	g.Define("object_type",
		Seq(
			Choice(
				Str("{"),
				Str("{|"),
			),
			Choice(
				Seq(
					Choice(
						Choice(
							Str(","),
							Str(";"),
						),
						Blank(),
					),
					Seq(
						Choice(
							Sym("export_statement"),
							Sym("property_signature"),
							Sym("call_signature"),
							Sym("construct_signature"),
							Sym("index_signature"),
							Sym("method_signature"),
						),
						Repeat(
							Seq(
								Choice(
									Str(","),
									Sym("_semicolon"),
								),
								Choice(
									Sym("export_statement"),
									Sym("property_signature"),
									Sym("call_signature"),
									Sym("construct_signature"),
									Sym("index_signature"),
									Sym("method_signature"),
								),
							),
						),
					),
					Choice(
						Choice(
							Str(","),
							Sym("_semicolon"),
						),
						Blank(),
					),
				),
				Blank(),
			),
			Choice(
				Str("}"),
				Str("|}"),
			),
		))

	g.Define("call_signature",
		Sym("_call_signature"))

	g.Define("property_signature",
		Seq(
			Choice(
				Sym("accessibility_modifier"),
				Blank(),
			),
			Choice(
				Str("static"),
				Blank(),
			),
			Choice(
				Sym("override_modifier"),
				Blank(),
			),
			Choice(
				Str("readonly"),
				Blank(),
			),
			Field("name",
				Sym("_property_name"),
			),
			Choice(
				Str("?"),
				Blank(),
			),
			Field("type",
				Choice(
					Sym("type_annotation"),
					Blank(),
				),
			),
		))

	g.Define("type_parameters",
		Seq(
			Str("<"),
			Seq(
				Sym("type_parameter"),
				Repeat(
					Seq(
						Str(","),
						Sym("type_parameter"),
					),
				),
			),
			Choice(
				Str(","),
				Blank(),
			),
			Str(">"),
		))

	g.Define("type_parameter",
		Seq(
			Choice(
				Str("const"),
				Blank(),
			),
			Field("name",
				Sym("_type_identifier"),
			),
			Field("constraint",
				Choice(
					Sym("constraint"),
					Blank(),
				),
			),
			Field("value",
				Choice(
					Sym("default_type"),
					Blank(),
				),
			),
		))

	g.Define("default_type",
		Seq(
			Str("="),
			Sym("type"),
		))

	g.Define("constraint",
		Seq(
			Choice(
				Str("extends"),
				Str(":"),
			),
			Sym("type"),
		))

	g.Define("construct_signature",
		Seq(
			Choice(
				Str("abstract"),
				Blank(),
			),
			Str("new"),
			Field("type_parameters",
				Choice(
					Sym("type_parameters"),
					Blank(),
				),
			),
			Field("parameters",
				Sym("formal_parameters"),
			),
			Field("type",
				Choice(
					Sym("type_annotation"),
					Blank(),
				),
			),
		))

	g.Define("index_signature",
		Seq(
			Choice(
				Seq(
					Field("sign",
						Choice(
							Choice(
								Str("-"),
								Str("+"),
							),
							Blank(),
						),
					),
					Str("readonly"),
				),
				Blank(),
			),
			Str("["),
			Choice(
				Seq(
					Field("name",
						Choice(
							Sym("identifier"),
							Alias(
								Sym("_reserved_identifier"),
								"identifier", true,
							),
						),
					),
					Str(":"),
					Field("index_type",
						Sym("type"),
					),
				),
				Sym("mapped_type_clause"),
			),
			Str("]"),
			Field("type",
				Choice(
					Sym("type_annotation"),
					Sym("omitting_type_annotation"),
					Sym("adding_type_annotation"),
					Sym("opting_type_annotation"),
				),
			),
		))

	g.Define("array_type",
		Seq(
			Sym("primary_type"),
			Str("["),
			Str("]"),
		))

	g.Define("tuple_type",
		Seq(
			Str("["),
			Choice(
				Seq(
					Sym("_tuple_type_member"),
					Repeat(
						Seq(
							Str(","),
							Sym("_tuple_type_member"),
						),
					),
				),
				Blank(),
			),
			Choice(
				Str(","),
				Blank(),
			),
			Str("]"),
		))

	g.Define("readonly_type",
		Seq(
			Str("readonly"),
			Sym("type"),
		))

	g.Define("union_type",
		PrecLeft(0,
			Seq(
				Choice(
					Sym("type"),
					Blank(),
				),
				Str("|"),
				Sym("type"),
			),
		))

	g.Define("intersection_type",
		PrecLeft(0,
			Seq(
				Choice(
					Sym("type"),
					Blank(),
				),
				Str("&"),
				Sym("type"),
			),
		))

	g.Define("function_type",
		PrecLeft(0,
			Seq(
				Field("type_parameters",
					Choice(
						Sym("type_parameters"),
						Blank(),
					),
				),
				Field("parameters",
					Sym("formal_parameters"),
				),
				Str("=>"),
				Field("return_type",
					Choice(
						Sym("type"),
						Sym("asserts"),
						Sym("type_predicate"),
					),
				),
			),
		))

	g.Define("_type_identifier",
		Alias(
			Sym("identifier"),
			"type_identifier", true,
		))

	g.SetExtras(
		Sym("comment"),
		Sym("html_comment"),
		Pat(`[\s\p{Zs}\uFEFF\u2028\u2029\u2060\u200B]`),
	)

	g.SetConflicts(
		[]string{"primary_expression", "_property_name"},
		[]string{"primary_expression", "_property_name", "arrow_function"},
		[]string{"primary_expression", "arrow_function"},
		[]string{"primary_expression", "method_definition"},
		[]string{"primary_expression", "rest_pattern"},
		[]string{"primary_expression", "pattern"},
		[]string{"primary_expression", "_for_header"},
		[]string{"variable_declarator", "_for_header"},
		[]string{"array", "array_pattern"},
		[]string{"object", "object_pattern"},
		[]string{"assignment_expression", "pattern"},
		[]string{"assignment_expression", "object_assignment_pattern"},
		[]string{"labeled_statement", "_property_name"},
		[]string{"computed_property_name", "array"},
		[]string{"binary_expression", "_initializer"},
		[]string{"class_static_block", "_property_name"},
		[]string{"call_expression", "instantiation_expression", "binary_expression"},
		[]string{"call_expression", "instantiation_expression", "binary_expression", "unary_expression"},
		[]string{"call_expression", "instantiation_expression", "binary_expression", "update_expression"},
		[]string{"call_expression", "instantiation_expression", "binary_expression", "await_expression"},
		[]string{"class"},
		[]string{"nested_identifier", "nested_type_identifier", "primary_expression"},
		[]string{"nested_identifier", "nested_type_identifier"},
		[]string{"_call_signature", "function_type"},
		[]string{"_call_signature", "constructor_type"},
		[]string{"primary_expression", "_parameter_name"},
		[]string{"primary_expression", "_parameter_name", "primary_type"},
		[]string{"primary_expression", "literal_type"},
		[]string{"primary_expression", "literal_type", "rest_pattern"},
		[]string{"primary_expression", "predefined_type", "rest_pattern"},
		[]string{"primary_expression", "primary_type"},
		[]string{"primary_expression", "generic_type"},
		[]string{"primary_expression", "predefined_type"},
		[]string{"primary_expression", "pattern", "primary_type"},
		[]string{"_parameter_name", "primary_type"},
		[]string{"pattern", "primary_type"},
		[]string{"optional_tuple_parameter", "primary_type"},
		[]string{"rest_pattern", "primary_type", "primary_expression"},
		[]string{"object", "object_type"},
		[]string{"object", "object_pattern", "object_type"},
		[]string{"object", "object_pattern", "_property_name"},
		[]string{"object_pattern", "object_type"},
		[]string{"object_pattern", "object_type"},
		[]string{"array", "tuple_type"},
		[]string{"array", "array_pattern", "tuple_type"},
		[]string{"array_pattern", "tuple_type"},
		[]string{"template_literal_type", "template_string"},
		[]string{"jsx_opening_element", "type_parameter"},
		[]string{"jsx_namespace_name", "primary_type"},
	)

	g.SetExternals(
		Sym("_automatic_semicolon"),
		Sym("_template_chars"),
		Sym("_ternary_qmark"),
		Sym("html_comment"),
		Str("||"),
		Sym("escape_sequence"),
		Sym("regex_pattern"),
		Sym("jsx_text"),
		Sym("_function_signature_automatic_semicolon"),
		Sym("__error_recovery"),
	)

	g.SetInline("_expressions", "_semicolon", "_identifier", "_reserved_identifier", "_jsx_attribute", "_jsx_element_name", "_jsx_child", "_jsx_element", "_jsx_attribute_name", "_jsx_attribute_value", "_jsx_identifier", "_lhs_expression", "_type_identifier", "_jsx_start_opening_element")

	g.SetWord("identifier")

	g.SetSupertypes("statement", "declaration", "expression", "primary_expression", "pattern", "type", "primary_type")

	g.Precedences = [][]PrecEntry{
		{
			{Name: "member"},
			{Name: "template_call"},
			{Name: "call"},
			{IsSymbol: true, Name: "update_expression"},
			{Name: "unary_void"},
			{Name: "binary_exp"},
			{Name: "binary_times"},
			{Name: "binary_plus"},
			{Name: "binary_shift"},
			{Name: "binary_compare"},
			{Name: "binary_relation"},
			{Name: "binary_equality"},
			{Name: "bitwise_and"},
			{Name: "bitwise_xor"},
			{Name: "bitwise_or"},
			{Name: "logical_and"},
			{Name: "logical_or"},
			{Name: "ternary"},
			{IsSymbol: true, Name: "sequence_expression"},
			{IsSymbol: true, Name: "arrow_function"},
		},
		{
			{Name: "assign"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{Name: "member"},
			{Name: "template_call"},
			{Name: "new"},
			{Name: "call"},
			{IsSymbol: true, Name: "expression"},
		},
		{
			{Name: "declaration"},
			{Name: "literal"},
		},
		{
			{IsSymbol: true, Name: "primary_expression"},
			{IsSymbol: true, Name: "statement_block"},
			{Name: "object"},
		},
		{
			{IsSymbol: true, Name: "meta_property"},
			{IsSymbol: true, Name: "import"},
		},
		{
			{IsSymbol: true, Name: "import_statement"},
			{IsSymbol: true, Name: "import"},
		},
		{
			{IsSymbol: true, Name: "export_statement"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{IsSymbol: true, Name: "lexical_declaration"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{Name: "call"},
			{Name: "instantiation"},
			{Name: "unary"},
			{Name: "binary"},
			{IsSymbol: true, Name: "await_expression"},
			{IsSymbol: true, Name: "arrow_function"},
		},
		{
			{Name: "extends"},
			{Name: "instantiation"},
		},
		{
			{IsSymbol: true, Name: "intersection_type"},
			{IsSymbol: true, Name: "union_type"},
			{IsSymbol: true, Name: "conditional_type"},
			{IsSymbol: true, Name: "function_type"},
			{Name: "binary"},
			{IsSymbol: true, Name: "type_predicate"},
			{IsSymbol: true, Name: "readonly_type"},
		},
		{
			{IsSymbol: true, Name: "mapped_type_clause"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{IsSymbol: true, Name: "accessibility_modifier"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{Name: "unary_void"},
			{IsSymbol: true, Name: "expression"},
		},
		{
			{IsSymbol: true, Name: "extends_clause"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{Name: "unary"},
			{Name: "assign"},
		},
		{
			{Name: "declaration"},
			{IsSymbol: true, Name: "expression"},
		},
		{
			{IsSymbol: true, Name: "predefined_type"},
			{IsSymbol: true, Name: "unary_expression"},
		},
		{
			{IsSymbol: true, Name: "type"},
			{IsSymbol: true, Name: "flow_maybe_type"},
		},
		{
			{IsSymbol: true, Name: "tuple_type"},
			{IsSymbol: true, Name: "array_type"},
			{IsSymbol: true, Name: "pattern"},
			{IsSymbol: true, Name: "type"},
		},
		{
			{IsSymbol: true, Name: "readonly_type"},
			{IsSymbol: true, Name: "pattern"},
		},
		{
			{IsSymbol: true, Name: "readonly_type"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{IsSymbol: true, Name: "type_query"},
			{IsSymbol: true, Name: "subscript_expression"},
			{IsSymbol: true, Name: "expression"},
		},
		{
			{IsSymbol: true, Name: "type_query"},
			{IsSymbol: true, Name: "_type_query_subscript_expression"},
		},
		{
			{IsSymbol: true, Name: "nested_type_identifier"},
			{IsSymbol: true, Name: "generic_type"},
			{IsSymbol: true, Name: "primary_type"},
			{IsSymbol: true, Name: "lookup_type"},
			{IsSymbol: true, Name: "index_type_query"},
			{IsSymbol: true, Name: "type"},
		},
		{
			{IsSymbol: true, Name: "as_expression"},
			{IsSymbol: true, Name: "satisfies_expression"},
			{IsSymbol: true, Name: "primary_type"},
		},
		{
			{IsSymbol: true, Name: "_type_query_member_expression"},
			{IsSymbol: true, Name: "member_expression"},
		},
		{
			{IsSymbol: true, Name: "member_expression"},
			{IsSymbol: true, Name: "_type_query_member_expression_in_type_annotation"},
		},
		{
			{IsSymbol: true, Name: "_type_query_member_expression"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{IsSymbol: true, Name: "_type_query_subscript_expression"},
			{IsSymbol: true, Name: "subscript_expression"},
		},
		{
			{IsSymbol: true, Name: "_type_query_subscript_expression"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{IsSymbol: true, Name: "_type_query_call_expression"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{IsSymbol: true, Name: "_type_query_instantiation_expression"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{IsSymbol: true, Name: "type_query"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{IsSymbol: true, Name: "override_modifier"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{IsSymbol: true, Name: "decorator_call_expression"},
			{IsSymbol: true, Name: "decorator"},
		},
		{
			{IsSymbol: true, Name: "literal_type"},
			{IsSymbol: true, Name: "pattern"},
		},
		{
			{IsSymbol: true, Name: "predefined_type"},
			{IsSymbol: true, Name: "pattern"},
		},
		{
			{IsSymbol: true, Name: "call_expression"},
			{IsSymbol: true, Name: "_type_query_call_expression"},
		},
		{
			{IsSymbol: true, Name: "call_expression"},
			{IsSymbol: true, Name: "_type_query_call_expression_in_type_annotation"},
		},
		{
			{IsSymbol: true, Name: "new_expression"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{IsSymbol: true, Name: "meta_property"},
			{IsSymbol: true, Name: "primary_expression"},
		},
		{
			{IsSymbol: true, Name: "construct_signature"},
			{IsSymbol: true, Name: "_property_name"},
		},
	}

	g.BinaryRepeatMode = true

	return g
}
